language/intro_generative_ai_studio.md
- Added 2 new screenshots
- Updated a few descriptions to match with the screenshots
=> Updating language/intro_generative_ai_studio.md

language/examples/prompt-design/question_answering.ipynb, language/intro_prompt_design.ipynb
added extra info on Q&A evaluation for fuzzywuzzy
=> added extra info on Q&A evaluation for fuzzywuzzy

README.md
Very minor tweaks to the folder structure to improve the readability
=> improve folder structure visuals

language/intro_palm_api.ipynb
From TextGenerationModel class contextual help:
_DEFAULT_TEMPERATURE = 0.0
_DEFAULT_MAX_OUTPUT_TOKENS = 128
_DEFAULT_TOP_P = 0.95
_DEFAULT_TOP_K = 40
=> Change max_output_tokens default to 128

CONTRIBUTING.md, language/examples/prompt-design/ideation.ipynb, language/examples/prompt-design/question_answering.ipynb, language/examples/prompt-design/text_classification.ipynb, language/examples/prompt-design/text_extraction.ipynb, language/examples/prompt-design/text_summarization.ipynb, language/intro_palm_api.ipynb, language/intro_prompt_design.ipynb
Added contributor guide section
Edited ref links on all the notebooks
=> updating CONTRIBUTING.md and fixing issue#16

README.md, RESOURCES.md
1. Added RESOURCES.md file that contains a list of official Google Generative AI resources like product pages, documentation, videos, courses and more.
=> Added Google Generative AI resources

language/intro_palm_api.ipynb
- fixed minor issues in language/intro_palm_api.ipynb
=> fixed minor issues in some code cells

language/intro_palm_api.ipynb
- improved examples in intro_palm_api.ipynb
- added a few comments to encourage user experimentation with prompts
- moved down cell showing how to render Markdown in Jupyter
=> improved examples

RESOURCES.md
1. Added Generative AI Learning Path from Cloud Skills Boost.
2. Added 7 courses under the Generative AI Learning Path.
3. Removed Model Tuning Lab since it is not available.
=> Update RESOURCES.md with Generative AI Learning Path and courses

language/intro_palm_api.ipynb
Updated notebook with vertexai.init to make sure it can run on Colab.
=> updating notebook with vertexai.init

language/examples/prompt-design/ideation.ipynb, language/examples/prompt-design/question_answering.ipynb, language/examples/prompt-design/text_classification.ipynb, language/examples/prompt-design/text_extraction.ipynb, language/examples/prompt-design/text_summarization.ipynb, language/intro_palm_api.ipynb, language/intro_prompt_design.ipynb
Updated all notebooks and added vertexinit to work on Colab.
=> Updated notebooks with vertexinit

language/examples/tuning/getting_started_tuning.ipynb
=> Fix typo in getting_started_tuning.ipynb

language/examples/prompt-design/ideation.ipynb, language/examples/prompt-design/question_answering.ipynb, language/examples/prompt-design/text_classification.ipynb, language/examples/prompt-design/text_extraction.ipynb, language/examples/prompt-design/text_summarization.ipynb, language/examples/reference-architectures/question_answering_with_large_documents.ipynb, language/examples/tuning/getting_started_tuning.ipynb, language/intro_palm_api.ipynb, language/intro_prompt_design.ipynb
- added foundation notebook for question-answering using large document. 
- ran code quality check
- resolved all comments for LGTM 
- fixed vertex init import error in all notebooks.
=> reference-architectures: question answering notebook. 

language/examples/reference-architectures/summarization_with_large_documents.ipynb
Added summarization_with_large_doucments.ipynb to language/examples/reference-architectures folder
=> Added summarization with large documents notebook

RESOURCES.md
Updated the Generative AI Learning courses with new courses, removed modified links, etc.
=> Update RESOURCES.md with Generative AI Learning Path courses

language/examples/oss-samples/langchain/summarization_with_large_documents_langchain.ipynb
This PR is about a notebook that shows how to use LangChain with PaLM API to summarize large documents.
=> feat: summarization with large documents using langchain

README.md, language/README.md, language/examples/document-qa/question_answering_large_documents_langchain.ipynb, language/examples/document-summarization/summarization_large_documents_langchain.ipynb, language/examples/langchain/intro_langchain_palm_api.ipynb
- minor fixes to langchain notebook for spelling, grammar, and broken links
- added more links to READMEs throughout
- fixed cells where importing vertexai was using incorrect code
=> updates to READMEs; fixed typos and links

language/examples/reference-architectures/product_description_generator_image.ipynb
product_description_generator_image.ipynb
=> fixed minor issues

README.md, language/README.md, language/examples/langchain-intro/README.md
=> fixed readme

language/examples/langchain-intro/intro_langchain_palm_api.ipynb
=> added note for restart

language/examples/tuning/getting_started_tuning.ipynb
- Made some minor changes to improve consistency.
=> Updated tuning notebook

language/README.md
=> fix links on language/README.md

language/examples/tuning/getting_started_tuning.ipynb
=> minor fixes tuning notebook

gen-app-builder/search-web-app/README.md, gen-app-builder/search-web-app/templates/ekg.html, gen-app-builder/search-web-app/templates/index.html, gen-app-builder/search-web-app/templates/search.html
=> fix: Update Repo Link in Enterprise Search Demo

language/intro_generative_ai_studio.md
minor fix to broken link in language/intro_generative_ai_studio.md
=> fixed broken img link

gen-app-builder/search-web-app/README.md, gen-app-builder/search-web-app/consts.py, gen-app-builder/search-web-app/genappbuilder_utils.py, gen-app-builder/search-web-app/main.py, gen-app-builder/search-web-app/static/index.css, gen-app-builder/search-web-app/static/recommend.js, gen-app-builder/search-web-app/templates/ekg.html, gen-app-builder/search-web-app/templates/index.html, gen-app-builder/search-web-app/templates/recommend.html, gen-app-builder/search-web-app/templates/search.html
- Added new page for https://cloud.google.com/generative-ai-app-builder/docs/try-personalize
=> feat: Added Personalize/Recommendations to Gen App Builder Demo

gen-app-builder/search-web-app/README.md, gen-app-builder/search-web-app/genappbuilder_utils.py, gen-app-builder/search-web-app/static/index.css, gen-app-builder/search-web-app/static/recommend.js, gen-app-builder/search-web-app/templates/recommend.html
- Added description for Personalize in the Web Page
- Updated Dataset for Personalize
- Fixed Breaking API change for Enterprise Search
=> feat: Gen App Builder Web App Updates

gen-app-builder/retrieval-augmented-generation/examples/question_answering.ipynb
Updated based on [langchain PR](https://github.com/hwchase17/langchain/pull/7857)
=> Updated ES retriever import to use langchain version

language/examples/document-summarization/summarization_large_documents.ipynb
Function argument is "_summary_" while what is being used in the function is '_initial_summary_'. Fixing this.
=> Variable name in 'reduce' step

gen-app-builder/data-store-status-checker/data_store_checker.ipynb
=> fix: typo in data_store_checker.ipynb

gen-app-builder/chat-app/README.md, gen-app-builder/chat-app/src/routes/+page.svelte
- Add main div container/wrapper
- Fix nav bar spacing
- Fix hard-coded dimensions for images and divs
- Use flex instead of sidebar CSS
Deployed new version of app at https://gen-app-builder-chat.web.app/
=> [Gen App Builder Chat App] - Improve responsive behavior for divs, imgs, flex, containers, etc.

README.md, vision/getting-started/visual_question_answering.ipynb
- Added visual captioning notebook
- Added visual question answering notebook
- Updated README.md
=> Adding vision notebooks

language/getting-started/intro_palm_api.ipynb
added codey in intro_palm_api notebook
=> added codey in intro_palm_api notebook

speech/getting-started/speech_recognition.ipynb
This notebook demonstrates how to use Chirp for accurately converting voice to text.
=> feat: Adding Speech Recognition notebook using Chirp

search/web-app/README.md, search/web-app/genappbuilder_utils.py, search/web-app/requirements.txt, search/web-app/static/ekg.js, search/web-app/static/recommend.js, search/web-app/static/search.js, search/web-app/templates/ekg.html, search/web-app/templates/image-search.html, search/web-app/templates/index.html, search/web-app/templates/recommend.html, search/web-app/templates/search.html
- Add more explicit exception handling
- Add local deployment instructions in readme
- Add highlightjs copy to allow copying of JSON
=> Update Vertex AI Search Web App

search/web-app/consts.py, search/web-app/genappbuilder_utils.py, search/web-app/main.py, search/web-app/requirements.txt, search/web-app/static/index.css, search/web-app/templates/index.html, search/web-app/templates/recommend.html, search/web-app/templates/search.html
- Added a second search engine to the Custom UI that uses Advanced Indexing
- Deployed at: https://vertex-ai-search.web.app
=> feat: Add Extractive Answers to Custom UI in Web App

vector-search/intro-textemb-vectorsearch.ipynb
- Renamed the folder name to vector-search
- Reduced the sample row size and call rate due to the default quota.
=> Updated embvs tutorial

language/tuning/tuning_text_bison.ipynb
Minor fixes and updates for tuning_text_bison notebook:
- Removed some code. 
- Updated documentation
- Now using pipeline template
=> minor updates for tuning_text_bison notebook

search/README.md
https://github.com/GoogleCloudPlatform/generative-ai/blob/main/search/search-web-app → https://github.com/GoogleCloudPlatform/generative-ai/tree/main/search/web-app
=> fix: Broken Links to Search Web App Demo

search/retrieval-augmented-generation/examples/contract_analysis.ipynb, search/retrieval-augmented-generation/examples/question_answering.ipynb, search/retrieval-augmented-generation/examples/rag_google_documentation.ipynb
- Add Colab/Vertex links and `--upgrade --user` to installation on Contract Analysis
- Update AI Platform and LangChain Versions
=> fix: Add missing steps to RAG Notebooks

language/README.md
Fixing the link to the LangChain + Matching Engine notebook
=> Fixing link in the README.md

search/retrieval-augmented-generation/examples/rag_google_documentation.ipynb
- Originally created by @grivescorbett 
- Add vertex ai init (required for usage outside of Workbench)
- Moved project variable initialization out of COLAB specifically.
- Added URL txt file download (if the user didn't clone the whole repo)
- Code refactoring for readability/efficiency
=> fix: Updates to RAG Google Documentation Notebook

language/getting-started/intro_palm_api.ipynb
Fix for error where:
`embedding_model.get_embeddings(df.text.values)` was returning an error because the `get_embeddings` method now expects the argument to be a list, not just a raw string.
=> fix error with embeddings model

README.md, language/README.md, language/code/README.md, language/code/code_chat.ipynb, language/code/code_completion.ipynb, language/code/code_generation.ipynb, language/code/code_retrieval_augmented_generation.ipynb
Added Codey Notebooks: 
language/code/
- [Notebook] Introduction to Code Chat
- [Notebook] Introduction to Code Completion
- [Notebook] Introduction to Code Generation
- [Notebook] Retrieval Augmented Generation (RAG) with Codey
=> Codey Notebooks

language/sample-apps/chat-flask-cloudrun/README.md, language/sample-apps/chat-gradio/README.md, language/sample-apps/chat-streamlit/README.md, language/sample-apps/code-predict-cloudfunction/README.md, language/sample-apps/summarization-gcs-cloudfunction/README.md, language/sample-apps/text-predict-cloudfunction/README.md
Updated the README file in all sample applications to include an informational message at the top that before the various commands are run, they will need to be in the correct folder. 
Often folks forget to be in the right application folder before executing the commands. This causes the commands to fail. The addition of the instruction above will help to ensure that the user is in the right folder and then the commands are run.
=> Updated README in all sample apps

embeddings/intro-textemb-vectorsearch.ipynb
- Updated code to change type from string into list 
- Updated timing of deployment
- Related Buganizer: http://b/311722941
=> Notebook Update: intro-textemb-vectorsearch.ipynb

embeddings/intro-textemb-vectorsearch.ipynb, embeddings/vector-search-quickstart.ipynb
corrected typo in the reminder to remove resources when done with the tutorial, specifically to delete the workbench instance
=> fix: Corrected typos in embeddings notebooks

gemini/sample-apps/README.md, gemini/sample-apps/SETUP.md, gemini/sample-apps/gemini-streamlit-cloudrun/README.md, gemini/sample-apps/gemini-streamlit-cloudrun/app.py, gemini/use-cases/retrieval-augmented-generation/intro_multimodal_rag.ipynb, language/code/code_chat.ipynb, language/code/code_completion.ipynb, language/code/code_generation.ipynb, language/code/code_retrieval_augmented_generation.ipynb
=> Gemini & Palm bugfixes

embeddings/intro-textemb-vectorsearch.ipynb
=> Updated intro-textemb-vectorsearch.ipynb

README.md
- This video is about the repository
- https://www.youtube.com/watch?v=xT7WW2SKLfE
=> feat: Add Applied AI Summit Video - GenAI Developers Toolkit to README

gemini/getting-started/intro_gemini_curl.ipynb
Role "system" in no longer supported in chat. 
Remove it from the reference.
=> fix: remove not-supported system role

language/grounding/intro-grounding.ipynb
* Fixed incorrect syntax for multi-turn session with `chat-bison`
* Use latest version of `text-bison` and `chat-bison` models
* Updated Python lib to latest version
* Fix consistency of output for responses and response metadata
=> Updates to Grounding notebook

.github/linters/.jscpd.json, search/web-app/consts.py, search/web-app/genappbuilder_utils.py, search/web-app/main.py, search/web-app/requirements.txt, search/web-app/static/index.css, search/web-app/static/search.js, search/web-app/templates/search.html
- Add [Summary Model Version](https://cloud.google.com/generative-ai-app-builder/docs/get-search-summaries#summary-model) Options (stable and preview)
- Add [Custom summarization preamble](https://cloud.google.com/generative-ai-app-builder/docs/get-search-summaries#custom-summaries)
Deployed at https://vertex-ai-search-demo-lnppzg3rxa-uc.a.run.app/search
=> feat: [VAIS - Web App Demo] Add summary customization

gemini/sample-apps/gemini-streamlit-cloudrun/app.py
Fixed spelling for video_geolocation.
=> Fixed "video_geolocation" spell mistake.

gemini/use-cases/retrieval-augmented-generation/intro_multimodal_rag.ipynb, gemini/use-cases/retrieval-augmented-generation/utils/intro_multimodal_rag_utils.py, language/sample-apps/chat-streamlit/Dockerfile, language/sample-apps/chat-streamlit/app.py, language/sample-apps/chat-streamlit/requirements.txt
=> fix: Fixed Lint/Format Errors

language/tuning/tuning_text_bison.ipynb
- Fix Links to renamed notebook
Fixes #140
=> fix: Replace preview `TextGenerationModel` with GA

gemini/use-cases/retrieval-augmented-generation/utils/intro_multimodal_rag_utils.py
fixed issues that broke the mrag utils.py
=> mrag_bugfix

search/create_datastore_and_search.ipynb
Added missing import statement for ClientOptions in create_datastore_and_search.ipynb
=> Added missing import statement for ClientOptions in create_datastore_and_search.ipynb

gemini/getting-started/intro_gemini_python.ipynb
- Added a command to install protobuf
- Reference bug: http://b/322748639
=> GSP1209 - Notebook updates

speech/use-cases/storytelling/storytelling.ipynb
Note: Added link/custom-made logo for Colab Enterprise and added SVG logos for Colab, Vertex AI Workbench, Github to improve quality/reduce space.
Moving & converting files from https://github.com/GoogleCloudPlatform/document-ai-samples/tree/main/play-reader into a Jupyter Notebook
Planned future expansions:
- Upload audio to Cloud Storage
- Read in story text using [Document AI OCR](https://cloud.google.com/document-ai)
- Convert any story to play script format using Gemini.
- Alternative: Use Gemini to generate [SSML](https://cloud.google.com/text-to-speech/docs/ssml) directly from book text?
- Create alternative implementation using LangChain.
- Assign character voices using Gemini.
- Add [Journey voices](https://cloud.google.com/text-to-speech/docs/voice-types#journey_voices) once …
=> feat: Add Storytelling Notebook using Text-to-Speech

search/custom-embeddings/custom_embeddings.ipynb, search/web-app/templates/index.html
- Updated Widget Link in Web App
- Added information about deployment and link to sample app in Custom Embeddings Notebook
=> chore: Vertex AI Search Updates

language/README.md, language/translation/intro_translation.ipynb
- Uses the [Cloud Translation API](https://cloud.google.com/translate?hl=en) to demonstrate language translation and Glossaries
=> feat: Add Intro to Translation Notebook

search/bulk-question-answering/bulk_question_answering.ipynb
- Added install for `google-auth`
- Removed my Project ID
- Minor formatting fixes
=> fix: Updates to VAIS Bulk Question Answering

search/web-app/README.md
=> fix: VAIS Web App - Add information about policies

gemini/README.md, gemini/evaluation/evaluate_gemini_with_autosxs.ipynb
This notebook demostrates how to use Vertex AI Model Evaluation AutoSxS for comparing models and check human alignment in a summarization task.
=> feat: Evaluate Gemini with AutoSxS

language/prompts/examples/text_summarization.ipynb
- Updated the hyperlinks
- Reference bug: http://b/324851669
=> GenAI: Notebook updates

gemini/use-cases/retail/multimodal_retail_recommendations.ipynb
Updated model names in text and code, fixed Workbench link, and added Colab Enterprise link
=> Chore: update model name in retail notebook

gemini/function-calling/intro_function_calling.ipynb
Main changes:
1) dropping "preview" from vertexai namespace
2) changing text references to include version (e.g. "Gemini Pro" -> "Gemini 1.0 Pro")
3) changing model IDs in code to include version (e.g. "gemini-pro" -> "gemini-1.0-pro")
4) updating top buttons to include a "Run in Colab Enterprise" link for the notebook
5) making sure the Workbench link actually points to a valid file on GitHub
Couple other minor edits made along the way, too.
=> Updating notebooks for Gemini Pro GA

gemini/use-cases/healthcare/react_gemini_healthcare_api.ipynb
Updated model names in text and code, fixed Workbench link, and added Colab Enterprise link
=> Chore: update model name in healthcare notebook

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml
Follow-up to #415
Fixes #383 🦕
=> chore: Add Issue Report Config and fix bug-report.yaml syntax issue

language/code/code_retrieval_augmented_generation.ipynb
Fixes #409 🦕
- Other Formatting and Readability improvements
=> fix: Updates to Codey RAG Notebook

gemini/function-calling/sql-talk-app/app.py
=> fix: crash for missing key when description of table is not set

language/prompts/intro_prompt_design.ipynb
=> fix: Set `protobuf` version to `3.19.3`

language/prompts/intro_prompt_design.ipynb
- Added shapely dependency to lower than version 2
- Reference bug: http://b/328420624
=> Notebook updates: intro_prompt_design.ipynb

language/prompts/intro_prompt_design.ipynb
=> Fix description of few-shot in intro_prompt_design.ipynb

vision/getting-started/visual_question_answering.ipynb
- Add GCS URI loading
- Formatting & Linting improvements
=> fix: Updates to Imagen Notebooks

gemini/function-calling/sql-talk-app/app.py
improve data format and handling
from `[Row((3.85, datetime.date(2024, 3, 12)), {'max_day_cap': 0, 'timestamp': 1})]`
when the model understood 0 and 1 as values from the column order, and wasn't picking up the real values from row object. 
to 
`[{'max_day_cap': 3.85, 'timestamp': datetime.date(2024, 3, 12)}]`
=> Improve function calling accuracy when pulling SQL results

search/search_data_blending_with_gemini_summarization.ipynb
- Changed to use `discoveryengine_v1alpha` client library
- Formatting/refactoring for readability/efficiency
- Prompt / Query Update to show results
=> fix: Updates to Search Blended Data Summarization

gemini/function-calling/sql-talk-app/app.py
- Enhanced the SQL query execution process by introducing query cleaning steps. This includes removing newline characters (`\n` and `\\n`) and backslashes (`\\`) from the query string to prevent errors related to formatting and escaping.
- Added a try-except block to handle exceptions during the query execution phase. Any encountered exceptions are now caught, and the error message is stored as the API response. This allows for model to understand the error and reattempt
- Modified the string representation of the API response to remove backslashes and newline characters, ensuring a cleaner output for logging purposes.
- These changes aim to improve the robustness of SQL query execution and error handling in the system, making the process more reliable and the logs more readable.
Thank …
=> feat(bigquery): enhance SQL query execution and error handling

gemini/use-cases/retrieval-augmented-generation/utils/__init__.py
=> add missing __init__.py file

search/web-app/README.md, search/web-app/consts.py, search/web-app/genappbuilder_utils.py, search/web-app/main.py, search/web-app/requirements.txt, search/web-app/static/search.js
- Update needed for Blended Search Support
- https://cloud.google.com/generative-ai-app-builder/docs/preview-search-results
=> fix: Update Vertex AI Search Web App Demo to use Engine ID

notebook_template.ipynb
Add a new notebook template:
- Standardize the Open links
- Reduce boilerplate
- Simplify the setup
- Standardize the setup with the vertex-ai-samples and the generative-ai repos
=> feat: Add notebook template

gemini/language/prompts/intro_prompt_design.ipynb
Migrates PaLM based text prompt design [notebook](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/prompts/intro_prompt_design.ipynb) to Gemini.
=> feat: add gemini intro prompt design notebook

gemini/language/prompts/examples/ideation.ipynb
Migration of PaLM [notebook](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/prompts/examples/ideation.ipynb) to use Gemini and new notebook template.
=> feat: add Gemini prompt ideation notebook

notebook_template.ipynb
Add information about enabling Vertex AI API.
=> refactor: Update template with information about enabling API

notebook_template.ipynb
Minor wording change for clarity.
=> chore: update template instructions

gemini/function-calling/intro_function_calling.ipynb
Fixes #473 by adding a custom user agent header to the API request.
=> fix: Add user agent header to sample API call w/ requests

gemini/prompts/examples/text_classification.ipynb
Adding sample notebook for text classification using Gemini model
=> feat: Add `text_classification using Gemini` notebook

gemini/prompts/examples/question_answering.ipynb, gemini/prompts/examples/text_extraction.ipynb, gemini/prompts/examples/text_summarization.ipynb
Adding following notebooks
text_summarization.ipynb: Text summarization use-case using Gemini
text_extraction.ipynb: Text extraction use-case using Gemini
question_answering.ipynb: Question answering use-case using Gemini
=> feat: Add Gemini based notebooks for prompt design

gemini/use-cases/retrieval-augmented-generation/rag_vector_embedding_in_bigquery.ipynb
- cleaning up a bunch of things, including "embeddings" (with an "s") throughout
- making sure code uses flags set earlier in notebook instead of hard-coded versions
- making it so notebook runs in Workbench
- uses ML.GENERATE_TEXT_EMBEDDING on all references for consistency
=> fix: Cleanup, changes after reviewing RAG in BQ notebook

gemini/use-cases/data-augmentation/data_augmentation_for_text.ipynb
Use peek() rather than head() for improved performance, per feedback
=> chore: Update data_augmentation_for_text.ipynb

gemini/function-calling/function_calling_data_structures.ipynb, notebook_template.ipynb
Fixes typos in the following notebooks:
- `gemini/function-calling/function_calling_data_structures.ipynb`
- `notebook_template.ipynb`
=> fix: Correct typos in `function_calling_data_structures` and `notebook_template` notebooks

gemini/function-calling/function_calling_data_structures.ipynb, gemini/function-calling/intro_function_calling.ipynb
* Reworked Intro to Function Calling notebook to reorder sections by dev usage patterns, updated terms and explanations for consistency, added example of chained function call, more descriptive section headers, and a different use case for entity extraction
* Collapse cell/form for Colab in Function Calling Data Structure notebook
=> refactor: Rework Intro to Function Calling notebook

gemini/tuning/supervised_finetuning_using_gemini.ipynb
This notebook demonstrates how to fine-tune the Gemini generative model using the Vertex AI Supervised Tuning feature.
- [] Your account is listed in [`CODEOWNERS`](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/.github/CODEOWNERS) for the file(s).
=> feat: Add `supervised_finetuning_using_gemini` notebook

gemini/use-cases/document-processing/sheet_music.ipynb, gemini/use-cases/video-analysis/video_analysis.ipynb
Used in Next 2024 session "What's next with Gemini: Driving business impact with multimodal use cases"
=> feat: Added Sheet Music and Video Analysis with Gemini

gemini/tuning/supervised_finetuning_using_gemini.ipynb
Updated broken links in notebooks and replaced 'Train steps' with 'Number of epochs' for clarity.
=> fix: Fixed broken links to the documentation, refined terminology

gemini/function-calling/sql-talk-app/README.md, gemini/use-cases/code/analyze_codebase_with_gemini_1_5_pro.ipynb
Add a new notebook for codebase analysis with Gemini 1.5 Pro.
=> feat: Add new notebook for codebase analysis with Gemini 1.5

gemini/grounding/intro-grounding-gemini.ipynb
Changing out 1 link on grounding from PaLM to Gemini
=> fix: Update intro-grounding-gemini.ipynb

gemini/evaluation/evaluate_gemini_with_autosxs.ipynb
=> feat: Update the autosxs notebook with the latest template

embeddings/get_started_with_embedding_tuning.ipynb, embeddings/intro_embeddings_tuning.ipynb
- Fixing the DocAIParser from LangChain
- Removing unnecessary helper function
=> fix: dependecies and helper - get started with embeddings tuning

language/prompts/intro_prompt_design.ipynb
- Added note to ignore pip dependency warnings.
- Buganizer: http://b/335798871
=> fix: GSP1151-Generative AI with Vertex AI: Prompt Design (Notebook update)

gemini/evaluation/get_started_with_genai_model_eval_service.ipynb
=> fix: typo, change llm_model to llm1_model

gemini/evaluation/evaluate_generated_answers_from_RAG_for_QA_rapid_evaluation_sdk.ipynb, gemini/evaluation/evaluate_rag_rapid_evaluation_sdk.ipynb
Add RAG QA evaluation notebook tutorial for Vertex AI Python SDK for Rapid Evaluation
=> feat: add Rapid Evaluation SDK tutorial for RAG QA evaluation

gemini/function-calling/forced_function_calling.ipynb
Add a sample notebook for using different Function Calling modes in Gemini, including forced function calling with the `ANY` mode, the default `AUTO` mode, and disabling Function Calling with `NONE` mode.
=> feat: Add sample notebook for forced Function Calling in Gemini

gemini/sample-apps/genwealth/api/package-lock.json, gemini/sample-apps/genwealth/api/package.json
Reverts GoogleCloudPlatform/generative-ai#605
=> Revert "chore(deps): update dependency typescript to v5"

gemini/tuning/gemini_supervised_tuning_qa.ipynb
=> adding tuning notebook

.github/CODEOWNERS, gemini/tuning/gemini_supervised_tuning_qa.ipynb, gemini/use-cases/retrieval-augmented-generation/rag_qna_langchain_bigquery_vector_search.ipynb
Update the notebook `Augment Q&A Generation using LangChain 🦜️🔗 and BigQuery Vector Search` with new dependency and retire deprecated methods
=> feat: update the notebook with new dependency and retire deprecated methods

gemini/use-cases/retrieval-augmented-generation/utils/intro_multimodal_rag_utils.py
PDFs with blank pages generate errors. Fix the support to process PDFs with blank pages.
=> fix: update intro_multimodal_rag_utils.py to support PDFs with blank pages

gemini/use-cases/retrieval-augmented-generation/small_to_big_rag/small_to_big_rag.ipynb
=> fix: Change `gemini_inference()` method definition

gemini/use-cases/applying-llms-to-data/analyze-poster-images-in-bigquery/poster_image_analysis.ipynb
Remove language about reservation requirement as this has been removed
=> fix: update Services and Costs documentation with new requirements

gemini/grounding/intro-grounding-gemini.ipynb
- Added citation output for Gemini Grounding.
- Updated model to Gemini 1.5 Pro
- Added more explanations about Grounding with Google Search Allowlist
- Fixed some copy/paste mistakes from PaLM Grounding notebook
Fixes #641 🦕
=> feat: Add Citations to Grounding with Gemini Notebook

RESOURCES.md
Updated Documentation links, Skills Boost courses, Video Playlists, Cloud NEXT 24 Gen AI Playlists and more for Generative AI offerings on Google Cloud.
=> feat: Update RESOURCES.md

gemini/use-cases/retrieval-augmented-generation/rag_qna_langchain_bigquery_vector_search.ipynb
=> fix: naming of embedding model to align with blog post

gemini/use-cases/retail/product_listing_generation.ipynb
Add a new notebook to generate a product listing for an e-commerce use case.
=> feat: add a new notebook to generate a product listing

gemini/sample-apps/genwealth/function-scripts/analyze-prospectus/main.py
=> feat: Speed up prospectus analysis and improve overview prompt.

language/prompts/intro_prompt_design.ipynb
- Removed the hardcoded region from the notebook.
- Reference buganizer: http://b/332832235
=> fix: intro_prompt_design.ipynb

gemini/function-calling/function_calling_data_structures.ipynb, gemini/function-calling/intro_function_calling.ipynb, gemini/function-calling/use_case_company_news_and_insights.ipynb
=> fix: Update Function Calling notebooks to Gemini 1.5 Pro (Preview)

vision/getting-started/image_editing.ipynb
=> fix: formatting indent and authors

gemini/use-cases/code/analyze_codebase_with_gemini_1_5_pro.ipynb
Update Gemini 1.5 Pro model to the latest version
=> fix: update Gemini 1.5 Pro model version

gemini/use-cases/multimodal_use_cases_workshop.ipynb
Add a new notebook for a workshop to run through multimodal prompts and use cases.
=> feat: add a new notebook for a multimodal use cases workshop

.github/ISSUE_TEMPLATE/bug-report.yml, .gitignore, README.md, gemini/README.md, gemini/sample-apps/fixmycar/cloud-sql/README.md, gemini/sample-apps/fixmycar/cloud-sql/backend/src/main/java/com/cpet/fixmycarbackend/FixMyCarBackendController.java, gemini/sample-apps/fixmycar/manuals/manual.md, gemini/sample-apps/genwealth/README.md, gemini/sample-apps/genwealth/api/index.ts, gemini/sample-apps/genwealth/ui/src/app/investments/investments.component.html, gemini/sample-apps/genwealth/ui/src/app/investments/investments.component.ts, gemini/sample-apps/genwealth/ui/src/styles.scss, gemini/sample-apps/genwealth/walkthroughs/backend-demo-walkthrough.md, gemini/sample-apps/genwealth/walkthroughs/frontend-demo-walkthrough.md, gemini/sample-apps/image-bash-jam/README.md, gemini/use-cases/applying-llms-to-data/using-gemini-with-bigquery-remote-functions/README.md, gemini/use-cases/applying-llms-to-data/using-gemini-with-bigquery-remote-functions/bigquery.tf, gemini/use-cases/retrieval-augmented-generation/utils/intro_multimodal_rag_utils.py, language/README.md, language/orchestration/langchain/README.md, language/sample-apps/.cctemplate, language/sample-apps/chat-streamlit/app.py, language/use-cases/document-qa/utils/matching_engine.py, language/use-cases/document-qa/utils/matching_engine_utils.py, search/web-app/ekg_utils.py, search/web-app/main.py, search/web-app/templates/ekg.html
Fixes misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
The misspellings have been reported at https://github.com/jsoref/generative-ai/actions/runs/9089326626#summary-24980320554
The action will report that the changes in this PR would make it happy: https://github.com/jsoref/generative-ai/actions/runs/9089326687#summary-24980320973
=> chore: fix spelling

gemini/getting-started/intro_gemini_1_5_flash.ipynb
- Based on Gemini 1.5 Pro Notebook
=> feat: Add Gemini 1.5 Flash Intro Notebook

gemini/README.md
Updated README.md to improve navigation within the generative-ai/gemini folder. 
Changes include:
Navigation Links: Added entries for key subfolders (getting-started, sample-apps, use-cases, evaluation, function-calling, grounding, responsible-ai, reasoning-engine, prompts, qa-ops, tuning) with descriptions and links. 
Folder Descriptions: Provided brief summaries of the purpose and contents of each subfolder. 
Table Layout:  Organized folders, descriptions, and links into a table for better readability.
=> chore: Update gemini/README.md

.github/actions/spelling/allow.txt, .github/workflows/spelling.yaml
=> fix: Update spell dictionaries

vision/use-cases/advanced_prompting_for_imagen2.ipynb
=> fix: fixed `light` spelling

gemini/use-cases/sheets-integration/Code.gs
Better handling for empty or invalid inputs
=> fix: update gemini-sheets integration

.github/actions/spelling/allow.txt, .github/actions/spelling/expect.txt, embeddings/use-cases/outlier-detection/bq-vector-search-log-outlier-detection.ipynb, notebook_template.ipynb
=> fix: update notebook github link to run in colab and others

notebook_template.ipynb
made edits to be in compliance with style guide
=> fix: Update notebook_template.ipynb

.github/actions/spelling/allow.txt, gemini/use-cases/document-processing/document_processing.ipynb
- Change Model to Gemini 1.5 Flash
- Fix behavior for Non-JSON output
- Replaced deleted document
- Fix prompt for Document Classification
- Removed PDF display
=> fix: Updates to Document Processing Notebook

.github/actions/spelling/allow.txt, gemini/responsible-ai/gemini_safety_ratings.ipynb
=> feat: updates with probablity and severity info

gemini/prompts/intro_prompt_design.ipynb
This PR fixes the following issues in the [Prompt Design - Best Practices](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/prompts/intro_prompt_design.ipynb):
- actually generate a hallucination to demonstrate how LLMs can hallucinate
- introduce system instructions as one way to reduce hallucinations or responding to irrelevant questions
- improve language for clarity
Other formatting & readability fixes
=> fix: generate hallucinations intentionally in prompt design notebook

gemini/evaluation/get_started_with_genai_model_eval_service.ipynb, gemini/function-calling/intro_function_calling.ipynb
=> fix: update the notebook with the new Eval classes and clean some typos

gemini/use-cases/code/code_scanning_and_vulnerability_detection.ipynb
=> fix: Update text in Code Analysis notebook

gemini/sample-apps/gemini-streamlit-cloudrun/README.md
Simplify the Cloud Run deploy step by skipping the reference --platform=managed
=> docs(gemini-streamlit-cloudrun): No need to specify --platform=managed

gemini/context-caching/intro_context_caching.ipynb
Add intro to context caching notebook to demonstrate on how to create and use context caching.
Fixes b/349619036 🦕
=> feat: Add intro to context caching notebook

gemini/controlled-generation/intro_controlled_generation.ipynb
Add a multimodality example for controlled generation.
- Object detection
=> feat: add multimodality example for controlled generation

gemini/prompts/examples/question_answering.ipynb, gemini/sample-apps/gemini-streamlit-cloudrun/README.md, gemini/sample-apps/gemini-streamlit-cloudrun/app.py
Other refactoring/updates for readability & usability.
- Allow users to select which model they use for each page.
Fixes #814 🦕
=> chore: Update Gemini Streamlit Cloud Run App to use Gemini 1.5 Flash & Pro

language/prompts/examples/question_answering.ipynb
=> fix: removing installation as a user

gemini/reasoning-engine/tracing_agents_in_reasoning_engine.ipynb
This is a tiny followup PR to #824 to fix the author table at the top of the sample notebook. I fixed the author table in the notebook template, but forgot to fix it in this notebook! 🤦
=> fix: Adjust formatting in Reasoning Engine sample notebook on tracing

gemini/getting-started/intro_gemini_1_5_flash.ipynb
=> fix(minor): update grammar in prompt

gemini/evaluation/evaluate_langchain_chains.ipynb
=> fix: hyperlinks eval langchain notebook

gemini/function-calling/intro_function_calling.ipynb
Added a note about temperature parameter and CTA at the end of function calling notebook.
=> docs: Added a note about temperature parameter and CTA

gemini/reasoning-engine/tracing_agents_in_reasoning_engine.ipynb
The "Open in Colab" link is missing the file extension.
Fixes #850  🦕
=> Fix colab link

.github/actions/spelling/line_forbidden.patterns, README.md
=> chore: Add forbidden patterns for Branding Guidelines

gemini/chat-completions/intro_chat_completions_api.ipynb
Add quickstart notebook for the Chat Completions API.
This is a public preview feature.
=> feat: add quickstart notebook for the chat completions api

gemini/use-cases/applying-llms-to-data/analyze-poster-images-in-bigquery/poster_image_analysis.ipynb
=> feat: Update to use Gemini 1.5 Flash

search/retrieval-augmented-generation/examples/question_answering.ipynb
Fixed doc error, changed model name from PaLM2 to Gemini.
=> docs: fixed a small documentation error

gemini/evaluation/evaluate_langchain_chains.ipynb
fix: evaluate_langchain_chains.ipynb aiplatform version
Set to pull latest
=> fix: evaluate_langchain_chains.ipynb aiplatform version

gemini/use-cases/applying-llms-to-data/analyze-poster-images-in-bigquery/poster_image_analysis.ipynb
=> fix: modify response into JSON format

.github/actions/spelling/allow.txt, gemini/tuning/vertexai_supervised_tuning_token_count_and_cost_estimation.ipynb
=> feat: Adding a notebook on token count and cost for tuning

gemini/grounding/intro-grounding-gemini.ipynb
=> fix: Remove extra project init for Grounding

language/prompts/intro_prompt_design.ipynb
=> fix: Update prompt_design notebook to use latest version of vertex ai sdk

.github/workflows/lint-notebooks.yaml
=> chore: Add Notebook Linter

gemini/function-calling/sql-talk-app/setup.sh
=> fix: Update sql-talk-app/setup.sh to enable bigquerydatatransfer

gemini/use-cases/retrieval-augmented-generation/rag_qna_with_bq_and_featurestore.ipynb
- Fix version libraries to point to latest
- Fix location variable. Notebook was using Region but region is not defined yet
=> fix: Update rag_qna_with_bq_and_featurestore.ipynb

gemini/reasoning-engine/intro_reasoning_engine.ipynb, gemini/reasoning-engine/tutorial_google_maps_agent.ipynb, gemini/reasoning-engine/tutorial_vertex_ai_search_rag_agent.ipynb
This PR fixes multiple issues in the Reasoning Engine sample notebooks:
* Update function name for creating satellite maps in https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/reasoning-engine/tutorial_google_maps_agent.ipynb
* Fix link to Vertex AI Search tutorial with structured data in https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/reasoning-engine/tutorial_vertex_ai_search_rag_agent.ipynb
* Add section on "Cleaning up" to multiple Reasoning Engine notebooks
=> fix: Various fixes and updates to Reasoning Engine sample notebooks

gemini/reasoning-engine/tutorial_cloud_sql_pg_rag_agent.ipynb
=> fix: typo in GCS bucket name for Cloud SQL Reasoning Engine tutorial

gemini/reasoning-engine/tutorial_alloydb_rag_agent.ipynb
=> fix: typo in GCS bucket name for AlloyDB Reasoning Engine tutorial

gemini/function-calling/use_case_company_news_and_insights.ipynb
Remove duplicated lines as function_call is defined just two lines above before the if.
=> fix: Remove duplicated function_call definition

gemini/sample-apps/fixmycar/manuals/GenerateMockAutoManual.ipynb
This is one of a series of model freshness update to use the latest models or model versions.
=> refactor: update to the latest models (3)

gemini/prompts/intro_prompt_design.ipynb
This is one of a series of model freshness update to use the latest models or model versions.
=> refactor: update to the latest models (1)

gemini/reasoning-engine/tutorial_alloydb_rag_agent.ipynb
=> fix: add `--quiet` to clean up step

gemini/qa-ops/building_DIY_multimodal_qa_system_with_mRAG.ipynb, gemini/use-cases/retrieval-augmented-generation/intro_multimodal_rag.ipynb
=> fix: Fix inclusion of Project ID in MM RAG notebooks

CONTRIBUTING.md, notebook_template.ipynb
=> fix: Update Contributing Guide to show notebook linter command and `nox -s format`

.github/actions/spelling/line_forbidden.patterns, README.md
=> ci: Added spelling check for Google-internal links

search/web-app/README.md
=> fix: Add more specific information and links for VAIS in web-app

embeddings/intro_embeddings_tuning.ipynb, gemini/getting-started/intro_gemini_chat.ipynb
Update the Gemini models used in the notebook to Gemini 1.5 Pro
=> chore: update model versions to Gemini 1.5

notebook_template.ipynb
Modify the notebook template to enable notebook testing. Change PROJECT_ID and LOCATION cells to use environment variables if the user doesn't provide a Project ID. Add a cell to load models in the template to incorporate the isTemplate field.
=> feat: add isTemplate var to notebook template

language/use-cases/sql-code-generation/sql_code_generation.ipynb
This PR adds the discontinuation banner for PaLM API to the language/use-cases/sql-code-generation/sql_code_generation.ipynb
Additionally, it removes unnecessary defined variables to pass linter test.
=> chore: Add PaLM Discontinuation Announcement Banner to PaLM Notebooks

search/README.md, search/vertexai-search-options/vertexai_search_options.ipynb
=> fix spell checks, links

gemini/grounding/intro-grounding-gemini.ipynb
Changed Grounding citations to use `grounding_supports` instead of `grounding_attributions`
Fixes #688 🦕
Fixes #692 🦕
=> fix: Update Grounding Intro with new Citations

language/code/code_retrieval_augmented_generation.ipynb
Update the notebook title from "with Codey APIs" to "with Gemini APIs" as the model has been updated.
=> chore: update the notebook title

gemini/use-cases/code/code_retrieval_augmented_generation.ipynb
Copy the code rag notebook to the gemini directory after we updated the notebook to gemini. It will make it easier to retire the PaLM directory after PaLM discontinues.
=> chore: copy code rag notebook to gemini directory after updated to gemini

gemini/prompts/examples/ideation.ipynb, gemini/prompts/examples/question_answering.ipynb, gemini/prompts/examples/text_classification.ipynb, gemini/prompts/examples/text_extraction.ipynb, gemini/prompts/examples/text_summarization.ipynb
Continue to update Gemini models used in notebooks to Gemini 1.5.
=> chore: Update Gemini models to 1.5

gemini/controlled-generation/intro_controlled_generation.ipynb
Added more examples for the new controlled generation features (b/364962330)
- Gemini 1.5 Flash support
- nullable
- text/x.enum
=> feat: Added more examples for new controlled generation features

search/retrieval-augmented-generation/examples/question_answering.ipynb, search/retrieval-augmented-generation/examples/rag_google_documentation.ipynb, search/search_data_blending_with_gemini_summarization.ipynb
Update Gemini models to 1.5.
Add discontinuation banner for PaLM
=> chore: Update models to Gemini 1.5

gemini/reasoning-engine/tutorial_alloydb_rag_agent.ipynb, gemini/reasoning-engine/tutorial_cloud_sql_pg_rag_agent.ipynb
=> chore: add private ip restriction note to LangChain on VertexAI RAG tutorials

gemini/evaluation/evaluate_rag_gen_ai_evaluation_service_sdk.ipynb
=> docs: Add more obvious regression examples to Rag notebook

embeddings/intro_embeddings_tuning.ipynb
=> feat: update embeddings tuning notebook

embeddings/vector-search-quickstart.ipynb
chore: update 404 link in vector-search-quickstart.ipynb
=> chore: update 404 link in vector-search-quickstart.ipynb

.github/actions/spelling/allow.txt
=> feat: add moviepy, fontdict to allow.txt

gemini/batch-prediction/intro_batch_prediction.ipynb, gemini/use-cases/video-analysis/youtube_video_analysis.ipynb
=> feat: Adding YouTube video analysis notebook

gemini/getting-started/intro_gemini_python.ipynb
Add examples for direct analysis of publicly available web media:
1. Image
2. Video + Controlled generation
=> feat: Add examples for direct analysis of publicly available web media

gemini/long-context/intro_long_context.ipynb
Update long context window information for Gemini 1.5.
Gemin 1.5 Flash 1M
Gemini 1.5 Pro 2M
=> refactor: Update long context window information

gemini/tuning/supervised_finetuning_using_gemini.ipynb
Supervised finetuning using gemini-1.5-pro-002
=> update: markdown

gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_ui.ipynb
=> feat: add gemini-1.5-pro:002 to the prompt optimizer notebook.

gemini/getting-started/intro_gemini_1_5_flash.ipynb
Use a stable version of Gemini 1.5 models to mitigate instability issues.
=> fix: Use a stable version of Gemini 1.5 models

gemini/tuning/vertexai_supervised_tuning_token_count_and_cost_estimation.ipynb
=> minor updates

gemini/getting-started/intro_gemini_python.ipynb
Add safety settings changes for the new Gemini 1.5 Flash 002 and Gemini 1.5 Pro 002 models:
- The safety settings are `OFF` by default 
- The default block thresholds are `BLOCK_NONE`
=> feat: Add safety settings changes for the new models

gemini/reasoning-engine/tutorial_alloydb_rag_agent.ipynb, gemini/reasoning-engine/tutorial_cloud_sql_pg_rag_agent.ipynb
=> fix: update Reasoning Engine tutorials with LangChain packages

gemini/orchestration/intro_langchain_gemini.ipynb
=> docs: Example Selectors page has moved

gemini/evaluation/compare_generative_ai_models.ipynb
Adding `plotly` as the notebook fails otherwise.
=> fix: Update compare_generative_ai_models.ipynb

gemini/tuning/supervised_finetuning_using_gemini_on_image_data.ipynb
Update the author section with correct markdown format.
Update Tuning section with additional info
=> update: markdown 

lychee.toml
=> ci: Remove medium.com from lychee checks

gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk.ipynb, gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk_custom_metric.ipynb
A quick fix for libraries import and quota banner to prevent quota error. 
=> fix: Libraries import and quota banner

gemini/tuning/supervised_finetuning_using_gemini_qa_ipynb.ipynb
=> New notebook on fine-tuning gemini 1.5 flash for qa

gemini/tuning/supervised_finetuning_using_gemini_qa_ipynb.ipynb
=> minor fixes

gemini/tuning/supervised_finetuning_using_gemini_qa.ipynb
=> minor updates and fixes

README.md
Remove third column (Same for most folders) and shorten description of `language/` directory.
=> docs: Update Directory table in README.md

gemini/getting-started/intro_gemini_1_5_flash.ipynb
The PDF analysis with both PDF and images scenario is consistently failing on Flash model so temporary remove the scenario from the example.
=> fix: Remove a problematic scenario for Gemini Flash model

gemini/sample-apps/e2e-gen-ai-app-starter-pack/README.md
quick fix to guide the user to setup their quota project before using the starter pack.
=> fix: README.md GenAI starter pack - setup quota project

gemini/sample-apps/e2e-gen-ai-app-starter-pack/README.md, gemini/sample-apps/e2e-gen-ai-app-starter-pack/deployment/README.md, gemini/sample-apps/e2e-gen-ai-app-starter-pack/deployment/terraform/build_triggers.tf, gemini/sample-apps/e2e-gen-ai-app-starter-pack/deployment/terraform/dev/apis.tf, gemini/sample-apps/e2e-gen-ai-app-starter-pack/deployment/terraform/dev/iam.tf, gemini/sample-apps/e2e-gen-ai-app-starter-pack/deployment/terraform/dev/log_sinks.tf, gemini/sample-apps/e2e-gen-ai-app-starter-pack/deployment/terraform/dev/service_accounts.tf, gemini/sample-apps/e2e-gen-ai-app-starter-pack/deployment/terraform/dev/storage.tf, gemini/sample-apps/e2e-gen-ai-app-starter-pack/poetry.lock, gemini/sample-apps/e2e-gen-ai-app-starter-pack/pyproject.toml
Originated from early user feedback
=> fix: readme, python version, terraform

gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk.ipynb, gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk_custom_metric.ipynb
Some fixes for notebooks in this PR. 
=> fix: libraries, variables and typos

gemini/rag-engine/intro_rag_engine.ipynb
Removed llamaindex and added RAG description
=> fix: Update intro_rag_engine.ipynb

gemini/responsible-ai/react_rag_attacks_mitigations_examples.ipynb
Bugs fix and structure improvement
=> fix: Bugs fix and structure improvement

gemini/sample-apps/e2e-gen-ai-app-starter-pack/tests/unit/test_server.py
Allow unit tests to seamless support chains using embeddings without raising errors due mocking
=> fix: support unit tests for chains using embeddings

gemini/reasoning-engine/tutorial_alloydb_rag_agent.ipynb
Missing import in the AlloyDB RAG tutorial needed for connecting to DB.
=> fix: add import in alloydb RAG tutorial

gemini/evaluation/evaluate_multimodal_task_image.ipynb
This notebook shows how to use Vertex AI Python SDK for Gen AI Evaluation Service for evaluating multimodal task with your locally-defined `CustomMetric`, and use your own autorater model to perform model-based metric evaluation.
=> feat: evaluating multimodel task 

gemini/evaluation/evaluate_models_in_vertex_ai_studio_and_model_garden.ipynb
=> fix: remove experiment run name configuration

noxfile.py
=> ci: Change `nox -s format` to only run on changed files

vision/use-cases/hey_llm/README.md, vision/use-cases/hey_llm/src/main.ts, vision/use-cases/hey_llm/src/sidebar.html
Add optional args for HEY_LLM and IMAGEN to let users specify other models in Vertex AI.
=> feat: Make models configurable for HEY_LLM and IMAGEN

gemini/reasoning-engine/tutorial_alloydb_rag_agent.ipynb
=> chore: fix typo in Reasoning Engine tutorial

vision/use-cases/hey_llm/src/main.ts, vision/use-cases/hey_llm/src/sidebar.html
This change lets spreadsheet owners preset OAuth information when deploying a spreadsheet.
=> feat: make OAuth client information presettable

partner-models/claude/computer-use-demo/cloudbuild.yaml
remove local dockerfile build and update to pull from ghcr for claude computer use demo
=> fix: remove local dockerfile build and update to pull from ghcr

gemini/sample-apps/e2e-gen-ai-app-starter-pack/README.md
=> feat: starter pack add video walkthrough

.github/actions/spelling/allow.txt, search/create_datastore_and_search.ipynb
Fixes #1339
- Added ADC authentication
- Changed Search to use Engine
=> fix: Update Create Data Store/Search Notebook

.github/CODEOWNERS, gemini/sample-apps/llamaindex-rag/backend/indexing/vector_search_utils.py
=> fix: correct deployment status validation

gemini/use-cases/retrieval-augmented-generation/rag_with_bigquery.ipynb
=> fix: Updates notebook to use different input PDF, adds processor cleanup

.github/CODEOWNERS, gemini/sample-apps/llamaindex-rag/backend/indexing/vector_search_utils.py
The previous code was retrieving the names before creating them.
=> fix: Retrieve list of index and endpoint names after creating the index and endpoint

.github/actions/spelling/allow.txt, gemini/tuning/supervised_finetuning_using_gemini_qa.ipynb
=> fix: updating fine-tuning notebook for qa

vision/use-cases/hey_llm/README.md, vision/use-cases/hey_llm/src/main.ts
Add `aspectRatio` argument to the IMAGEN function.
=> feat: add aspect ratio argument to IMAGEN

embeddings/vector-search-quickstart.ipynb
Making the variable names less confusing and adding explanation around difference between INDEX_NAME and DEPLOYED_INDEX_ID.
Actual changes view to make it easier for reviewers:
=> fix(vector-search-quickstart): Making the variable names less confusing and adding explanation

gemini/prompts/prompt_optimizer/vapo_lib.py
Update the regex logic in the validate_prompt_and_data function to properly handle JSON string in the prompt template.
=> fix: update the prompt template regex to handle JSON string

gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk.ipynb, gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk_custom_metric.ipynb, gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_ui.ipynb
Add the controlled generation support in the prompt optimization notebooks.
=> fix: add the controlled generation support in the notebooks

gemini/rag-engine/rag_engine_feature_store.ipynb, rag-grounding/README.md
https://cloud.google.com/vertex-ai/generative-ai/docs/use-feature-store-with-rag
=> feat: Notebook for RAG Engine with Feature Store

noxfile.py
=> ci: Update noxfile to exclude deleted files

vision/use-cases/hey_llm/src/main.ts
Extend the cache expiration for HEY_LLM / IMAGEN.
=> feat: Longer cache duration for HEY_LLM

vision/use-cases/hey_llm/package-lock.json, vision/use-cases/hey_llm/src/main.ts
- Include inputs in the log when any error occurred
- Add `muteHttpExceptions: true` to all fetches
- Run `npm audit fix`
=> feat: Better logging for HEY_LLM

audio/speech/use-cases/podcast/multi-speaker-podcast.ipynb
Fixes #<This notebook demonstrates how to use the [Gemini API in Vertex AI](https://cloud.google.com/vertex-ai/generative-ai/docs/overview) to generate an engaging multi speaker podcast using studio voices [Text-to-Speech API](https://cloud.google.com/text-to-speech). This can be useful for creating interviews, interactive storytelling, video games, e-learning platforms, and accessibility solutions.> 🦕
=> fix: Multi speaker podcast using Gemini Control Generation & Speech to Text

gemini/evaluation/evaluate_translation.ipynb
feat: add public notebook showing how to use the Vertex AI SDK for evaluating translation quality of models using COMET and MetricX.
=> feat: add public notebook for evaluating translation quality of models using COMET and MetricX.

.github/actions/spelling/line_forbidden.patterns, gemini/evaluation/evaluate_rag_batch_pipeline.ipynb
=> feat: ragops batch evaluation pipeline

gemini/rag-engine/rag_engine_feature_store.ipynb
https://github.com/googleapis/python-aiplatform/releases/tag/v1.73.0
=> fix: Update RAG Feature Store notebook to use released library

.github/actions/spelling/allow.txt, open-models/README.md, open-models/serving/vertex_ai_pytorch_inference_paligemma_with_custom_handler.ipynb
This notebook showcases how to deploy Google PaliGemma from the Hugging Face Hub on Vertex AI using the Hugging Face Deep Learning Container (DLC) for Pytorch Inference in combination with a [custom handler](https://huggingface.co/docs/inference-endpoints/en/guides/custom_handler#create-custom-inference-handler).
=> feat: serving paligemma using HFDLC with custom handler 

gemini/sample-apps/e2e-gen-ai-app-starter-pack/RELEASES.md, gemini/sample-apps/e2e-gen-ai-app-starter-pack/poetry.lock, gemini/sample-apps/e2e-gen-ai-app-starter-pack/pyproject.toml
- Bump starter pack version to 0.2.0
- Introduce a RELEASES.md
=> feat: bump starter pack version to 0.2.0

gemini/sample-apps/e2e-gen-ai-app-starter-pack/README.md, gemini/sample-apps/e2e-gen-ai-app-starter-pack/app/patterns/agentic_rag_vertex_ai_search/README.md
adds minor info such as suggested environment where to run the starter pack and search pattern gif
=> feat: add minor info to starter pack readmes

open-models/serving/vertex_ai_pytorch_inference_paligemma_with_custom_handler.ipynb
This PR is about simplifying the notebook text. 
=> fix: remove some text

gemini/use-cases/diarized-transcription-summarization/diarized_transcription_and_summarization.ipynb
=> fix: text formatting and sub heading

.github/actions/spelling/allow.txt, open-models/evaluation/vertex_ai_tgi_gemma_with_genai_evaluation.ipynb
=> fix: removing some typos

.github/workflows/format.yaml
=> ci: Add formatter to run on all pull requests

gemini/use-cases/video-analysis/video_analysis_with_youtube_data_api_and_batch_prediction.ipynb
Fixes #<issue_number_goes_here> 🦕 (NA)
=> feat: add scaled video analysis NB (YT API + batch pred)

gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk.ipynb, gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk_custom_metric.ipynb, gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk_long_prompt_optimization.ipynb, gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk_tool_calling.ipynb
This PR is about fixing some typos in vapo notebooks. 
=> fix: Fix some typos in vapo notebooks

gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk_long_prompt_optimization.ipynb
This PR is about simplifying notebook documentation. 
=> fix: Simplify notebook documentation

.github/actions/spelling/allow.txt, gemini/multimodal-live-api/websocket-demo-app/README.md, gemini/multimodal-live-api/websocket-demo-app/index.html, gemini/multimodal-live-api/websocket-demo-app/main.py, gemini/multimodal-live-api/websocket-demo-app/pcm-processor.js, gemini/multimodal-live-api/websocket-demo-app/requirements.txt
=> feat: new demo for multimodal live api

gemini/agents/research-multi-agents/intro_research_multi_agents_gemini_2_0.ipynb
- [ Yes] Follow the [`CONTRIBUTING` Guide](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md).
- [ Yes] You are listed as the author in your notebook or README file.
- [ Yes] Your account is listed in [`CODEOWNERS`](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/.github/CODEOWNERS) for the file(s).
- [ Yes] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [ Yes] Ensure the tests and linter pass (Run `nox -s format` from the repository root to format).
- [ Yes] Appropriate docs were updated (if necessary)
=> fixing the folder download in multi-agent

gemini/multimodal-live-api/real_time_rag_bank_loans_gemini_2_0.ipynb
- [ YES] Follow the [`CONTRIBUTING` Guide](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md). 
- [ YES] You are listed as the author in your notebook or README file. 
- [ YES] Your account is listed in [`CODEOWNERS`](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/.github/CODEOWNERS) for the file(s). 
- [ YES] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification. 
- [ YES] Ensure the tests and linter pass (Run `nox -s format` from the repository root to format). 
- [ YES] Appropriate docs were updated (if necessary) 
=> adding gemini 2.0 use-case for financial services 

gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_ui.ipynb
Update the description about evaluation metrics, especially the MetricX.
=> fix: update the description about MetricX value

README.md
- code execution
- multimodal live api
- multimodal live api with SDK
=> docs: Update README.md with more Gemini 2.0 notebooks

gemini/multimodal-live-api/README.md
Add a README to the Multimodal Live API directory.
=> feat: add a README to multimodal live api directory

gemini/getting-started/intro_genai_sdk.ipynb
- Update notebook for breaking change in `google-genai` library
- https://github.com/googleapis/python-genai/blob/main/CHANGELOG.md#030-2024-12-17
- Changed Cache model to 1.5 Flash for speed
=> fix: Update Intro to Gen AI SDK for library update - Context Caching

gemini/sample-apps/swot-agent/README.md, gemini/sample-apps/swot-agent/agent.py, gemini/sample-apps/swot-agent/requirements.txt
Updated and tested dependencies. Required an API change in the use of the Google GenAI SDK.
=> chore: update swot-agent to latest dependencies

gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_ui.ipynb
The string type specification of the prompt template will treat "\n" as "\\n", which will cause issues in the regex processing.
=> fix: remove the string type specification of the prompt template in the UI notebook

audio/speech/use-cases/podcast/multi-speaker-podcast.ipynb
Multiple speaker generation requires allowlist, and we should make that clear in the notebook
=> fix: Update multi-speaker-podcast.ipynb with allowlist warning

gemini/code-execution/intro_code_execution.ipynb
- Change Code output to use Language syntax highlighting
=> fix: Updates to Code Execution Notebook

gemini/use-cases/applying-llms-to-data/bigquery_dataframes_ml_drug_name_generation.ipynb, language/use-cases/applying-llms-to-data/bigquery_dataframes_ml_drug_name_generation.ipynb
Ported Prescription Drug Name Generator with BigQuery DataFrames to Gemini 2.0
=> feat: Add Prescription Drug Name Generator with Gemini

open-models/serving/vertex_ai_tgi_gemma_multi_lora_adapters_deployment.ipynb
=> fix: use torch inference container

notebook_template.ipynb
=> fix: Update copyright year in Notebook Template

gemini/use-cases/retrieval-augmented-generation/rag-evaluation/deepeval_with_gemini.ipynb
=> FIX: small syntax error on deepeval install

open-models/use-cases/vertex_ai_deepseek_smolagents.ipynb
=> feat: add agent eval for deepseek agent

gemini/rag-engine/intro_rag_engine.ipynb
Small amendments to improve the `gemini/rag-engine/intro_rag_engine.ipynb` sample.
=> docs: RAG engine tidying

embeddings/large-embs-generation-for-vvs.ipynb
Confirmed with the product team that the batch prediction does:
- support multilingual model (so removing)
- not support task type (so we'll leave it as is)
=> fix: Update the intro text

.github/actions/spelling/allow.txt, gemini/use-cases/code/analyze_codebase_with_gemini_1_5_pro.ipynb
- Change Notebook to use Gen AI SDK
- Use gitingest to load repo contents into prompt
- Remove magika library and `extract_code()` method.
- Change GitHub issue pull to use automatic function calling
=> fix: Update Codebase Analysis NB to use Gen AI SDK and gitingest

gemini/sample-apps/gemini-streamlit-cloudrun/README.md
=> fix: Add Deploy to Cloud Run button for streamlit sample app

gemini/getting-started/intro_genai_sdk.ipynb
Add file argument and other fixes
=> fix: bug fixes to genai sdk intro notebook

gemini/agents/research-multi-agents/intro_research_multi_agents_gemini_2_0.ipynb, gemini/batch-prediction/intro_batch_prediction_using_bigquery_input_vertex_ai_sdk.ipynb, gemini/batch-prediction/intro_batch_prediction_vertex_ai_sdk.ipynb, gemini/context-caching/intro_context_caching_vertex_ai_sdk.ipynb, gemini/function-calling/intro_function_calling_vertex_ai_sdk.ipynb, gemini/grounding/intro_grounding_gemini_vertex_ai_sdk.ipynb, gemini/long-context/intro_long_context_vertex_ai_sdk.ipynb, gemini/prompts/intro_prompt_design_vertex_ai_sdk.ipynb, gemini/responsible-ai/gemini_safety_ratings_vertex_ai_sdk.ipynb
- Update banners with links from Vertex AI SDK Notebooks to Gen AI SDK notebooks
- Remove banner that says Gemini 2.0 Flash is experimental
=> chore: Update banners for notebooks

gemini/evaluation/evaluate_models_in_vertex_ai_studio_and_model_garden.ipynb
fix: remove inconsistent model variable naming in evaluate_models_in_vertex_ai_studio_and_model_garden.ipynb
Fixes #1691  🦕
=> fix: remove inconsistent model variable naming

gemini/sample-apps/gemini-quart-cloudrun/app/app.py, gemini/sample-apps/gemini-quart-cloudrun/app/public/index.html
=> fix: corrected web page title and reverted the model name to exp

.github/CODEOWNERS, rag-grounding/README.md
Small PR - Commit d77d3976078ab22c2756827154c6e1e56386ce0e moved the `cloud_run_ollama_gemma2_rag_qa.ipynb` notebook. This PR adjusts sources to changes.
=> fix: update Gemma 2 RAG Q&A with Ollama and LangChain notebook

gemini/grounding/intro-grounding-gemini.ipynb
Fixes a minor formatting issue in the intro to gemini grounding notebook.
Fixes #1724 🦕
=> fix: Update DATA_STORE_NAME formatting

workshops/qa-ops/building_DIY_multimodal_qa_system_with_mRAG.ipynb, workshops/qa-ops/intro_Vertex_AI_embeddings.ipynb
Follow-up to `2fd555a42e97dd1bd53f8d8d7c3dee08dcc10037`
=> chore: Move qa-ops to workshops folder

gemini/rag-engine/intro_rag_engine.ipynb, gemini/rag-engine/rag_engine_pinecone.ipynb, gemini/rag-engine/rag_engine_vector_search.ipynb
- Add Install of Google Gen AI SDK
- Update RAG Engine Syntax to GA version
=> chore: Update RAG Engine Notebooks to Gemini 2.0 and RAG Engine GA

gemini/evaluation/bring_your_own_autorater_with_custom_metric.ipynb, gemini/evaluation/bring_your_own_computation_based_metric.ipynb, gemini/evaluation/evaluate_gemini_tool_use.ipynb, gemini/evaluation/evaluate_langchain_chains.ipynb, gemini/evaluation/evaluate_models_in_vertex_ai_studio_and_model_garden.ipynb, gemini/evaluation/evaluate_rag_gen_ai_evaluation_service_sdk.ipynb
=> feat: update notebooks with eval SDK notebook_utils function

gemini/evaluation/compare_generative_ai_models.ipynb, gemini/evaluation/customize_model_based_metrics.ipynb, gemini/evaluation/evaluate_and_compare_gemini_model_settings.ipynb, gemini/evaluation/intro_to_gen_ai_evaluation_service_sdk.ipynb, gemini/evaluation/migration_guide_preview_to_GA_sdk.ipynb, gemini/evaluation/prompt_engineering_gen_ai_evaluation_service_sdk.ipynb, gemini/reasoning-engine/evaluating_langchain_agent_reasoning_engine_prebuilt_template.ipynb
=> feat: update notebooks with eval SDK helper functions

.github/actions/spelling/allow.txt
Add author names from citation for Mathvista dataset for Vertex AI Prompt Optimizer Multimodal Notebook.
=> feat: Update allow.txt

.github/actions/spelling/allow.txt, gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk_multimodal_image.ipynb
- [ X] Follow the [`CONTRIBUTING` Guide](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md).
- [X ] You are listed as the author in your notebook or README file.
- [ X] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [ X] Ensure the tests and linter pass (Run `nox -s format` from the repository root to format).
- [X ] Appropriate docs were updated (if necessary)
Fixes b376662590 🦕
=> feat: Add Vertex AI Prompt Optimizer multimodal notebook

.github/CODEOWNERS, gemini/use-cases/productivity/productivity_coaching_with_google_calendar_and_gmail.ipynb
=> feat: added producivity coaching use case

gemini/grounding/grounding_with_vais.ipynb
=> feat: Simplify the grounding with VAIS colab and fix syntax errors.

gemini/getting-started/intro_gemini_2_0_flash_rest_api.ipynb
=> fix: updating variable configuration to be consistent with other notebooks

.github/actions/spelling/allow.txt, vision/getting-started/veo2_video_generation.ipynb
New notebook for Veo 2 text to video generation with Gen AI SDK
=> feat: add Veo 2 video generation notebook

gemini/rag-engine/intro_rag_engine.ipynb
=> fix: Fix syntax error in RAG Engine Intro

gemini/multimodal-live-api/intro_multimodal_live_api_genai_sdk.ipynb
=> fix: Add Check for `None` in MM Live NB

gemini/evaluation/evaluating_crewai_agent.ipynb
Fixes #1784 🦕
Fixes #1784 🦕
Below is the evidence for the Fix
https://github.com/user-attachments/assets/f9feff35-48eb-439c-98b8-9cb11e3158ef
=> fix: Fix crewai tools import according to latest version of crewai (#1784)

.github/CODEOWNERS, embeddings/intro_embeddings_tuning.ipynb, gemini/agent-engine/README.md, gemini/agent-engine/intro_agent_engine.ipynb, gemini/agent-engine/langgraph_human_in_the_loop.ipynb, gemini/agent-engine/tracing_agents_in_agent_engine.ipynb, gemini/agent-engine/tutorial_alloydb_rag_agent.ipynb, gemini/agent-engine/tutorial_cloud_sql_pg_rag_agent.ipynb, gemini/agent-engine/tutorial_google_maps_agent.ipynb, gemini/agent-engine/tutorial_langgraph.ipynb, gemini/agent-engine/tutorial_langgraph_rag_agent.ipynb, gemini/agent-engine/tutorial_vertex_ai_search_rag_agent.ipynb, gemini/sample-apps/photo-discovery/README.md, search/vertexai-search-options/vertex_ai_search_website_summary.ipynb
This PR is a followup to #1787 with updates based on name changes to Agent Engine.
=> fix: Additional edits to Agent Engine names and links in sample notebooks

gemini/function-calling/use_case_company_news_and_insights.ipynb
- Updated the model from gemini-1.5 to gemini-2.0
=> fix: Updated the Gemini model to Gemini 2.0

rag-grounding/README.md
Small PR - Commit 190bb060f19b6943bf3a70509f9acd259da85a62 moved RAG related notebooks. This PR adjusts sources to changes.
=> fix: Update RAG related notebooks

embeddings/intro-textemb-vectorsearch.ipynb
- Update to Gen AI SDK
- Fix spelling errors
- Update images to HTML to make them smaller
- Update model to text-embedding-005
=> chore: Update intro-textemb-vectorsearch to Gen AI SDK

vision/getting-started/veo2_video_generation.ipynb
Add an additional example to the Veo 2 video generation notebook showcasing image to video
=> feat: image to video example

gemini/tuning/supervised_finetuning_using_gemini.ipynb, gemini/tuning/supervised_finetuning_using_gemini_on_image_data.ipynb
Updating the tuning notebooks to use Gen AI SDK
=> chore: Migrate Tuning Notebooks from Vertex AI SDK to Gen AI SDK

gemini/getting-started/intro_gemini_chat.ipynb
- Update Intro to Gemini Chat to Google Gen AI SDK
- Changed all printing to Markdown
- Added examples for Streaming Output and Multimodal Input
- Changed LangChain samples to use `MODEL_ID` constant
=> chore: Update Intro Gemini Chat to Google Gen AI SDK

open-models/serving/vertex_ai_pytorch_inference_paligemma_with_custom_handler.ipynb
=> fix: Add missing EOF to the paligemma notebook

gemini/grounding/grounding_with_vais.ipynb
=> fix: Fix grounding call typo

open-models/serving/vertex_ai_pytorch_inference_pllum_with_custom_handler.ipynb
=> fix: auto formatting broke the notebook

gemini/use-cases/video-thumbnail-generation/video_thumbnail_generation.ipynb
- Moved to Gemini directory because it doesn't use Imagen
=> chore: Update Video Thumbnail Generation to Gemini 2.0

gemini/getting-started/intro_gemini_2_5_pro.ipynb
Update 2.5 pro thinking model examples
- added Vertex AI references
- added thinking mode examples
- corrected max output tokens
=> chore: update 2.5 pro thinking model examples

.github/actions/spelling/allow.txt, gemini/getting-started/intro_gemini_2_0_image_gen.ipynb
---
Co-authored-by: Nikita Namjoshi <namjoshi.nikita@gmail.com>
=> feat: Add Gemini Image Generation Notebook

gemini/global-endpoint/intro_global_endpoint.ipynb
Add a new notebook for the Global Endpoint
Notes:
- Using curl for REST API and Gen AI SDK
- To update links to public docs when available
=> feat: Add Global Endpoint examples

open-models/serving/cloud_run_vllm_gemma3_inference.ipynb
Fix project id in Gemma + Cloud Run + vLLM notebook.
=> fix: project_id in Gemma + Cloud Run + vLLM notebook.

README.md
This is a useful learning resource for the Gemini SDK.
=> feat: Add Gemini By Example

gemini/agents/genai-experience-concierge/.gitignore, gemini/agents/genai-experience-concierge/README.md, gemini/agents/genai-experience-concierge/langgraph-demo/backend/Dockerfile, gemini/agents/genai-experience-concierge/langgraph-demo/backend/README.md, gemini/agents/genai-experience-concierge/langgraph-demo/frontend/Dockerfile, gemini/agents/genai-experience-concierge/langgraph-demo/frontend/README.md, gemini/agents/genai-experience-concierge/langgraph-demo/frontend/concierge_ui/demo_page.py
Fixes some broken links identified when deploying the concierge demo.
=> fix: Fix/remove broken concierge demo links

workshops/ai-agents/ai_agents_for_engineers.ipynb
Fixed ValidationError: Value error, Unable to find your project.
=> fix: ValidationError in AI Agents for Engineers

gemini/evaluation/evaluate_models_in_vertex_ai_studio_and_model_garden.ipynb
=> fix: update llama 3.1 maas model id name

gemini/model-optimizer/intro_model_optimizer.ipynb
=> refactor: intro_model_optimizer

gemini/model-optimizer/intro_model_optimizer.ipynb
=> fix: intro_model_optimizer

gemini/use-cases/customer-support/customer_support_gemini_genai_sdk.ipynb
A demo customer support use case, using
- multimodal reasoning
- image generation
- controlled generation
- google search
- function calling
- live api
- etc.
=> feat: Add a customer support use case for a demo

.github/actions/spelling/allow.txt, gemini/multimodal-live-api/gradio-voice/README.md, gemini/multimodal-live-api/gradio-voice/app.py, gemini/multimodal-live-api/gradio-voice/requirements.txt, gemini/multimodal-live-api/real_time_rag_bank_loans_gemini_2_0.ipynb, gemini/multimodal-live-api/real_time_rag_retail_gemini_2_0.ipynb, gemini/multimodal-live-api/websocket-demo-app/frontend/script.js, gemini/sample-apps/gemini-quart-cloudrun/app/app.py, gemini/sample-apps/swot-agent/agent.py
=> fix: Update Gemini Live API model to `gemini-2.0-flash-live-preview-04-09`

gemini/agent-engine/tutorial_mcp_toolbox_for_databases.ipynb
A tutorial of remotely deploying and communicating among:
* Postgresql database
* MCP toolbox for databases
* Agent engine.
Fixes b/408037871 🦕
=> feat: Tutorial mcp toolbox for databases in agent engine

audio/speech/sample-apps/live-translator/app.py
Use `st.audio_input()` so that we can record any length of audio to be translated
=> fix: use `st.audio_input()` to record any length of audio

gemini/getting-started/intro_gemini_2_0_flash.ipynb, gemini/getting-started/intro_gemini_2_0_flash_lite.ipynb, gemini/getting-started/intro_gemini_2_5_pro.ipynb
- Re-add Audio/Document examples to Gemini 2.5 Pro NB
=> chore: Change Image Download from `gsutil` to `wget`

gemini/use-cases/document-processing/summarization_large_documents_langchain.ipynb, rag-grounding/README.md
- Duplicate of https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/use-cases/document-summarization/summarization_large_documents_langchain.ipynb
- Moving for Skills Boost
=> feat: Text Summarization LangChain

.github/CODEOWNERS
Remove non-Google accounts from CODEOWNERS, sort and format
=> ci: Fix CODEOWNERS

gemini/use-cases/document-processing/document_processing.ipynb
Pull in features from https://github.com/GoogleCloudPlatform/applied-ai-engineering-samples/blob/main/genai-on-vertex-ai/gemini/prompting_recipes/pdf_processing/1_extract_pdf_pages_with_gemini.ipynb by @leiterenato
=> feat: Add PDF Page Extraction to Document Processing Notebook

gemini/global-endpoint/intro_global_endpoint.ipynb
Update the global endpoint notebook with links to public docs.
https://cloud.google.com/vertex-ai/generative-ai/docs/learn/locations
=> refactor: Update global endpoint with links to public docs

gemini/grounding/intro-grounding-gemini.ipynb
- Add in-line citations to Grounding output similar to Vertex AI Studio or Vertex AI Search UI
- Update `VertexAISearch` tool to use `engine` instead of `datastore`
=> feat: Add Citations Printing to Grounding Notebook

gemini/getting-started/intro_gemini_2_0_flash.ipynb, gemini/getting-started/intro_gemini_2_0_flash_lite.ipynb, gemini/getting-started/intro_gemini_2_5_flash.ipynb, gemini/getting-started/intro_gemini_2_5_pro.ipynb
Add example for sending a website HTML page to Gemini
=> fix: Add Website input to Gemini intro Notebooks

.github/actions/spelling/allow.txt, gemini/prompts/prompt_optimizer/vapo_lib.py, gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk_tool_calling.ipynb
=> fix: Parsing function in Prompt Optimizer

gemini/mcp/mcp_orchestration_app/README.md
=> fix: Updated README file instructions for clarity

.github/CODEOWNERS, .github/actions/spelling/allow.txt, search/custom-ranking/clearbox.ipynb
=> feat(search): Create Clearbox demo notebook

gemini/getting-started/intro_gemini_2_5_flash.ipynb
Add enabling thought summarization example for Gemini 2.5 Flash
Steaming only
=> feat: add enabling thought summarization example

gemini/getting-started/intro_gemini_2_5_pro.ipynb
Update Gemini 2.5 Pro model version to :
gemini-2.5-pro-preview-05-06
=> refactor: Update Gemini 2.5 Pro version

gemini/getting-started/intro_gemini_2_5_pro.ipynb
Add viewing summarized thoughts example for Gemini 2.5 Pro
- generate_content()
- generate_content_stream()
=> feat: Add summarized thoughts example for Gemini 2.5 Pro

gemini/grounding/intro-grounding-gemini.ipynb
Do not merge until https://github.com/googleapis/python-genai/commit/731c5a35ad4d48c324160e0686a6603d335ccd59 is released in `google-genai` on PyPi
=> feat: Add `EnterpriseWebSearch` in Gen AI SDK to Grounding NB

.github/actions/spelling/allow.txt, search/agentspace/agentspace_eval.ipynb
Added the agentspace eval example and followed all the documentation as suggested
=> feat: Agentspace Evaluation Notebook

gemini/chat-completions/intro_chat_completions_api.ipynb
Add extra_body parameter examples in the OpenAPI compatibility
- safety settings
- context caching
- controlled generation with list example
=> feat: Add extra_body parameter examples in the OpenAPI compability

gemini/getting-started/intro_gemini_2_5_flash.ipynb
fix: correct the max thinking budget
thinking_budget: [0-24576]
=> fix: correct the max thinking budget

audio/speech/use-cases/storytelling/storytelling.ipynb, gemini/chat-completions/intro_chat_completions_api.ipynb, gemini/getting-started/intro_gemini_2_5_flash.ipynb, gemini/sample-apps/gemini-streamlit-cloudrun/app.py
Gemini 2.5 Flash new preview model:
gemini-2.5-flash-preview-05-20
=> feat: Gemini 2.5 Flash new preview model

gemini/multimodal-live-api/intro_multimodal_live_api.ipynb, gemini/multimodal-live-api/intro_multimodal_live_api_genai_sdk.ipynb
Add native audio examples to Live API:
- Proactive Audio
- Affective Dialog
=> feat: Add native audio examples to Live API

audio/music/getting-started/lyria2_music_generation.ipynb
Add music generation notebook with Lyria 2
=> feat: lyria notebook

.github/actions/spelling/allow.txt, audio/music/getting-started/lyria2_music_generation.ipynb
Fix spelling in music generation notebook
=> fix: spelling in music notebook

vision/getting-started/imagen4_image_generation.ipynb
Add a new notebook for Imagen 4 image generation
=> feat:imagen 4 image notebook

vision/getting-started/veo3_video_generation.ipynb
Video generation notebook for Veo 3
=> feat: veo 3 notebook

.cloud-build/cloudbuild.yaml
=> ci: Update Notebook testing framework timeout

gemini/tuning/sft_gemini_summarization.ipynb
=> fix: change LOCATION to REGION

gemini/context-caching/intro_context_caching.ipynb
Add implicit caching example for context caching:
- Re-enable caching if needed (seen caching disabled for some projects)
- Use implicit caching and check cached tokens
- Fix an error in chat (wasn't using cache)
=> feat: add implicit caching example

gemini/context-caching/intro_context_caching.ipynb
Temporarily increase the implicit minimum size to 2k for Gemini 2.5 Flash.
- Update text
- Use a new image
=> fix: Update the implicit caching min size

gemini/multimodal-live-api/intro_multimodal_live_api_genai_sdk.ipynb
Add voice activity detection example for Live API
=> feat: Add voice activity detection example for Live API

vision/getting-started/imagen4_image_generation.ipynb
Update Imagen 4 image generation notebook to use the latest models. Include a new section on Imagen 4 Fast.
=> feat: update imagen models

gemini/getting-started/intro_gemini_2_5_flash.ipynb, gemini/getting-started/intro_gemini_2_5_flash_lite.ipynb, gemini/getting-started/intro_gemini_2_5_pro.ipynb, gemini/multimodal-live-api/intro_multimodal_live_api.ipynb, gemini/multimodal-live-api/intro_multimodal_live_api_genai_sdk.ipynb
Gemini model updates:
- Add new 2.5 Flash-lite
- Update 2.5 Pro
- Update 2.5 Flash
- Update Live API with native audio
=> feat: Update Gemini new models

vision/getting-started/veo2_advanced_controls.ipynb
=> fix: change notebook name

vision/getting-started/veo3_video_generation.ipynb
Add prompt enhancement techniques to Veo 3 video generation notebook
=> feat: add prompt enhancement to veo 3 notebook

.github/actions/spelling/allow.txt, open-models/agents/qwen3_adk_vertexai.ipynb
This tutorial demonstrates how to build an AI agent using Agent Development Kit (ADK) with Qwen3 model deployed on Vertex AI. Also, it shows how to deploy the agent as a scalable, production-ready service with Vertex AI Agent Engine.
=> feat: Qwen 3 with ADK on Agent Engine

.github/actions/spelling/allow.txt, gemini/agent-engine/memory/get_started_with_memory_bank_crewai.ipynb
This notebook is about Memory Bank integration with CrewAI. 
=> crewai notebook

agents/adk/README.md
Add ADK cross reference links in README.md under agents/adk
=> feat: Add ADK cross reference links

gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk.ipynb, gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk_custom_metric.ipynb, gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk_long_prompt_optimization.ipynb, gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk_multimodal_image.ipynb, gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_sdk_tool_calling.ipynb, gemini/prompts/prompt_optimizer/vertex_ai_prompt_optimizer_ui.ipynb
Add 2.5-flash-lite support in all PO notebooks
=> feat: add 2.5-flash-lite support in all po notebooks

.github/actions/spelling/allow.txt, .github/actions/spelling/expect.txt, search/agentspace/mcp_with_agentspace.ipynb, search/agentspace/oss_model_with_agentspace.ipynb
=> feat: OSS Models with Agentspace, Fix: Links, Code cleanup

vision/getting-started/virtual_try_on.ipynb
Set the parameters in the VTO prediction request.
=> fix: Set parameters in the prediction request.

vision/getting-started/veo3_video_generation.ipynb
=> feat: update veo3 model version

agents/agent_engine/tutorial_mcp_on_agent_engine.ipynb
=> fix services

.github/actions/spelling/allow.txt, gemini/tuning/sft_gemini_migration_recipe.ipynb, gemini/tuning/sft_gemini_on_image_captioning.ipynb
=> feat(gemini): update image captioning notebook to 2.5 Flash 

gemini/tuning/sft_gemini_migration_recipe.ipynb
=> minor updates to migration notebook

vision/getting-started/imagen_product_recontext.ipynb
Update the Imagen Product Recontext notebook to use the Gen AI SDK
=> feat: update product recontext notebook

vision/getting-started/imagen4_image_generation.ipynb, vision/getting-started/virtual_try_on.ipynb
Update Imagen 4, Imagen 4 Fast, and Imagen 4 Ultra model versions
=> feat: update Imagen 4 model

.github/actions/spelling/allow.txt, open-models/fine-tuning/get_started_with_oss_tuning_on_vertexai.ipynb
This notebook demonstrates how to reproduce the core ideas of the **MetaMath** paper by fine-tuning a Llama model on the `MetaMathQA` dataset using Vertex AI's managed service for open-source models.
=> feat: Vertex AI OSS Managed tuning - Reproducing MetaMath recipe

gemini/getting-started/intro_gemini_chat.ipynb
=> Add project parameter to `ChatVertexAI`

gemini/agent-engine/langgraph_human_in_the_loop.ipynb
Update the LanggraphAgent reference to use agent_engines module
=> fix: update LanggraphAgent reference to use agent_engines module

vision/getting-started/veo2_reference_to_video.ipynb
New notebook for Veo 2 Reference-to-Video feature. With this feature, you can supply up to three asset images or one style image and generate a new video from these references.
=> feat: veo 2 reference-to-video

embeddings/intro_multimodal_embeddings.ipynb
fix: Updating the embedding model name and image printing
=> fix: Updating the embedding model name and image printing

agents/gemini_data_analytics/intro_gemini_data_analytics_http.ipynb
=> Update default creator filter to NONE

README.md
Adds links to sister projects GenMedia Creative Studio and the MCP Tools for Genmedia, in https://github.com/GoogleCloudPlatform/vertex-ai-creative-studio
- [] You are listed as the author in your notebook or README file.
=> doc(readme): genmedia creative studio additions

gemini/url-context/intro_url_context.ipynb
Multiple tools with Google Search and URL Context is no longer a private/allowlisted feature. 
It is now enabled in API version v1beta1.
=> feat: enable Search+URL Context in API v1beta1

gemini/logging/intro_request_response_logging.ipynb
Add a new tutorial for the request and response logging feature for Gemini
- Preview
- Vertex AI SDK only
- Output to BigQuery
- Create BigQuery dataset automatically
=> feat: Add a new tutorial for the request and response logging feature

agents/agent_engine/memory_bank/tutorial_get_started_with_multimodal_agents_with_memory_bank.ipynb
A small PR to fix types and reorder cells. 
=> fix: Types fix and cell reordering

open-models/get_started_with_oss_maas_reasoning_open_ai_sdk.ipynb
This tutorial explains how to use reasoning capabilities with Model-as-a-Service (MaaS) models on Google Cloud's Vertex AI.
=> feat: Handling Reasoning with MaaS Models on Vertex AI using vLLM

.github/actions/spelling/allow.txt, gemini/use-cases/applying-llms-to-data/ai-assisted-data-science/ai-assisted-data-science.ipynb
=> feat: add AI assisted data science notebook

audio/speech/getting-started/get_started_with_gemini_tts_voices.ipynb
use GA model names without preview in them:
* gemini-2.5-flash-preview-tts -> gemini-2.5-flash-tts 
* gemini-2.5-pro-preview-tts -> gemini-2.5-pro-tts
=> update model names to GA

gemini/getting-started/intro_gemini_2_5_image_gen.ipynb
Add updates to Gemini 2.5 Flash Image notebook, including the GA model, aspect ratios, and image only outputs.
=> feat: Nano Banana feature updates

gemini/use-cases/applying-llms-to-data/ai-assisted-data-science/ai-assisted-data-science.ipynb
=> chore: updates notebook title and removes section numbers

open-models/get_started_with_model_garden_terraform_deployment.ipynb
This tutorial shows how to use Terraform to deploy open models from Vertex AI Model Garden.
=> feat: models as code with Vertex AI Model Garden
