README.md

Reference to CONTRIBUTING.md file has wrong url in README.md, have corrected with correct URL. 
Original URL: https://github.com/GoogleCloudPlatform/generative-ai/CONTRIBUTING.md
Correct URL: https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md

corrected CONTRIBUTING.md link in README.md file

---

gen-app-builder/retrieval-augmented-generation/utils/retriever.py

We recently updated our Enterprise Search response class to replace the `snippets` field with `extractive_segments` and `extractive_answers` which are specifically designed for consumption by LLMs. This was a breaking change, fixed by this PR

Updated Retriever class to support new API response fields

---

language/examples/tuning/getting_started_tuning.ipynb

Rolling back to preview to fix issue as reported here: 
https://github.com/GoogleCloudPlatform/generative-ai/discussions/146

tuning notebook: fix to import line and GCS bucket

---

language/examples/document-qa/question_answering_documents_langchain_matching_engine.ipynb

Including ""gs://" syntax. Else it throws the following error..
_CommandException: "mb" command does not support "file://" URLs. Did you mean to use a gs:// URL?_

Include full GCS path for gsutil command

---

search/web-app/README.md
search/web-app/templates/image-search.html

- This was supported before, but the description didn't say so. And a user got confused.
- Updated: https://vertex-ai-search.web.app/image-search

fix: Search Web App - Change Image Search to allow text queries

---

embeddings/embedding-similarity-visualization.ipynb
embeddings/intro-textemb-vectorsearch.ipynb
embeddings/vector-search-quickstart.ipynb

Copying the notebooks with a few fixes. After updating the existing links to the vertex-search notebooks on public documents, we will remove /vector-search folder and use /embeddings for future updates.

copying from vector-search to embedding

---

conversation/chat-app/src/routes/+page.svelte

Fixes #263 by switching to a different Data Store Agent indexed on Google Store.
Fixed version of the app is deployed to https://vertex-ai-conversation.web.app/.

Switch to different Data Store Agent in sample chat app

---

vector-search/intro-textemb-vectorsearch.ipynb

This pull request addresses a TypeError encountered in the `get_embeddings_wrapper` function within the Vertex AI vector search notebook. The error was caused by passing a pandas Series (df.title) directly to the function, which expects a list of strings.
Changes Made:
* Modified the call to `get_embeddings_wrapper` by converting the Series df.title to a list of strings using `tolist()`.
* This change ensures compatibility with the expected input format of the `model.get_embeddings` method, preventing the TypeError.
Verified that the `get_embeddings_wrapper` function now correctly processes a list of strings without throwing a TypeError, and confirmed that the embeddings are successfully retrieved and added to the DataFrame.

Fix TypeError in `get_embeddings_wrapper` by Ensuring List Input

---

embeddings/vector-search-quickstart.ipynb

(As requested after talking to Kaz Sato)
1. Switched `IAM` and `gcloud` command
2. Added 'Service Usage Admin' to the IAM permissions. This should unblock the `gcloud services enable ...` command.
3. Added some double quotes around variables in shell to make it safer to run these commands (impredictable behaviour if empty string).
Note this is needed in Workbench mode, since it runs as your compute Service Account. If it runs as you, you dont need any IAM powerup.

Fixed access issue on the workbench side.

---

gemini/sample-apps/gemini-streamlit-cloudrun/README.md

Cloud Shell will redirect localhost to forwarded port, and CORS needs to be disabled for that network route

Update README.md to work on Cloud-Shell

---

language/use-cases/document-qa/question_answering_documents_langchain.ipynb

This PR made two changes to the `language/examples/document-qa/question_answering_large_documents_langchain.ipynb` notebook:
1. It fixed the display error of the refine method outputs. The original code displayed outputs from the map reduce method instead of the refine method.
2. It changed the similarity search index part in the `Q&A with similarity search` section. This modification allows the `map_reduce_embeddings_outputs` to include source information such as page numbers, similar to the previous `map_reduce_outputs` and `refine_outputs`.
Following the Contributing Guide, I have submitted the CLA and ran the Code Quality Checks.
I kindly request you to review the changes at your convenience. Please let me know if there is anything else I can do to assist with the review process or …

Fix display error in refine method and enhance similarity search index with document metadata for document qa with langchain

---

language/grounding/intro-grounding.ipynb

Fixes #320 by adding details about the release stages of Grounding with Vertex AI Search vs. Grounding with Google Web Search Results.

Add note about early access for Grounding with Web Search

---

language/code/code_retrieval_augmented_generation.ipynb

url's were fixed for colab, github and workspace for codey RAG notebook.

fixed broken link - codey_rag

---

vision/gradio/gradio_image_generation_sdk.ipynb

Opening a PR for generative-ai/vision/gradio. Adding a new getting started sample notebook with Gradio and Imagen for image generation. This example provides a complete end to end example using Gradio and the **preview** Vertex AI SDK for image generation. Once ImageGenerationModel module from the Vertex AI SDK is GA will provide an updated sample.
Confirmed that this example passes required **code quality checks** documented in [CONTRIBUTING.md](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md)
Checklist
* [ X ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md#code-quality-checks).

feat: Adding a image generation notebook example for Imagen

---

language/getting-started/intro_palm_api.ipynb
language/orchestration/langchain/intro_langchain_palm_api.ipynb
language/prompts/intro_prompt_design.ipynb
language/use-cases/document-qa/question_answering_documents_langchain.ipynb
language/use-cases/document-qa/question_answering_documents_langchain_matching_engine.ipynb
language/use-cases/document-summarization/summarization_large_documents_langchain.ipynb
setup-env/README.md

In Jupiter notebooks tutorial examples [https://cloud.google.com/vertex-ai/docs/generative-ai/learn-resources](https://cloud.google.com/vertex-ai/docs/generative-ai/learn-resources) I was not able to authenticate in my local development environment. 
Current option was only for colab and workbench.
Found solution using google.oauth2 and service_account.
So I added commented authentication option for "other development environments" to jupyter notebooks tutorials.

Added authentication for other development environments in jupyter notebooks

---

gemini/getting-started/intro_gemini_python.ipynb

Reverts GoogleCloudPlatform/generative-ai#365
Based on @polong-lin 's comment in b/issues/322748639#comment6
> Actually pip install protobuf does not address the root cause, which I had fixed on Sunday: https://github.com/CloudVLab/terraform-lab-foundation/pull/353
>
> The User Managed Notebook Instance deployed in Qwiklabs was using an old VM image, which caused Python dependency conflicts with the latest version of Vertex AI. The notebook instance is deployed based on the terraform script here: https://github.com/CloudVLab/terraform-lab-foundation/tree/main/solutions/generative-ai/stable
>
> If a user uses a newer version of a User Managed Notebook instance or even a Workbench Instance, then users actually have no issue.
>
> Since the issue is limited to Qwiklabs due to the old image, I …

Revert "GSP1209 - Notebook updates"

---

gemini/function-calling/intro_function_calling.ipynb

Gemini will sometimes now return two or more subsequent function calls after a function response so that it can gather more information in a single conversation turn with the end user. This broke the simple example in the Gemini function calling notebook since (for the sake of simplicity) it assumes one function call per conversation turn.
```python
>>> response = chat.send_message(
>>>    Part.from_function_response(
>>>        name="place_order",
>>>        response={
>>>            "content": api_response,
>>>        },
>>>    ),
>>>)
>>>
>>>response.candidates[0].content.parts[0]
InvalidArgument: 400 Please ensure that function response turn comes immediately after a function call turn.
```
This PR simplifies one of the prompts to keep the conversation flow in the notebook on track …

[Gemini function calling] Simplify prompt in chat session to avoid multiple function calls

---

gemini/function-calling/sql-talk-app/app.py

A tiny followup PR to #385 that uses the appropriate exception handling to check if intermediate function calling outputs exist for a given conversation turn. Fixes an uncaught exception when doing 2 or more conversation turns.
Updated app version is deployed at https://sql-talk-r5gdynozbq-uc.a.run.app/

[Gemini function calling] Fix exception handling in app frontend code

---

gemini/use-cases/retrieval-augmented-generation/intro_multimodal_rag.ipynb
gemini/use-cases/retrieval-augmented-generation/utils/intro_multimodal_rag_utils.py

- Removed unused code blocks.
- “get_image_embedding_from_multimodal_embedding_model” now uses vertexai vision model MultiModalEmbeddingModel class.
- BugFix: The “get_image_metadata_df” function had a bug that resulted in missing images in image_metadata_df when two or more images are present on a single page. 
- Removed “mm_embedding_from_text_desc_and_img” embeddings from the image_metadata, as it is not being used and it doesn’t add value unless image captions are available and there needs to be search between captions. 
- Removed Stream=False block from “get_gemini_response” function. The default is Stream=True. 
- Removed “Project_id” from the notebook and utils. Now, it doesn’t require Project_id to do any processing. 
- Updated “GenerationConfig(temperature=0.2, …

fix: mRAG BugFix and QuickFixes

---

gemini/function-calling/intro_function_calling.ipynb

Modify the prompt in Intro to Function Calling notebook to avoid safety filters when geocoding address.

fix: Modify prompt related to geocoding address in `intro_function_calling` notebook

---

gemini/grounding/intro-grounding-gemini.ipynb

fix: Add note about Terms of Service for Grounding with Google Search

---

gemini/function-calling/function_calling_data_structures.ipynb
gemini/function-calling/intro_function_calling.ipynb
gemini/function-calling/sql-talk-app/app.py

Updates Gemini Function Calling notebooks to pin `gemini-1.0-pro-001` for consistent model behavior.

fix: Pin model version to `gemini-1.0-pro-001` for function calling notebooks

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml
CONTRIBUTING.md

* #383 said that the graphic should be updated -- for now, I think just deleting the reference to the graphic is a strict improvement.
* while looking for references to `dev`, I found two links to `discord` that somewhat confusingly redirect to discourse, so update the links and descriptions

docs: update contributing flow

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/actions/spelling/allow.txt

Issues are often reported in this repository that belong in other Google-owned GitHub repositories.
The issue template is an attempt to prevent these issues from being filed in the wrong place.

fix: Update Issue templates to include `google-gemini` and `python-aiplatform`

---

.github/actions/spelling/allow.txt
gemini/function-calling/sql-talk-app/app.py

This PR bumps the version of the Gemini model used in the SQL Talk sample app for Function Calling in Gemini from `gemini-1.0-pro-001` to `gemini-1.5-pro-001`.

fix: Update model version to Gemini 1.5 Pro in SQL Talk app

---

gemini/grounding/intro-grounding-gemini.ipynb

According to the release note https://cloud.google.com/vertex-ai/generative-ai/docs/release-notes#May_14_2024 the **Grounding with Google Search** feature should be in GA.
I updated the parts of the documentation, where it is still referring to Preview status. I assume that the Terms of Service (pointing to the Preview Terms) are not required anymore.

fix: Update intro-grounding-gemini.ipynb

---

gemini/sample-apps/gemini-streamlit-cloudrun/README.md

This change removes the build step for the Cloud Run deployment instructions. Instead, the Cloud Run deploy uses a source deploy, where Cloud Run's CLI operation manages the steps to upload and build the container image for use.
This simplifies the instructions and accelerates folks to using the sample app more quickly.

docs(gemini-streamlit-cloudrun): Remove separate build step

---

gemini/prompts/examples/question_answering.ipynb

Fixing FuzzyWuzzy source library availability. 
QwickLabs were failing.  
This is the latest (2020) stable library that is available at the official github repo
Fixes #NA 🦕

fix: question_answering.ipynb with a working fuzzywuzzy lib location

---

gemini/reasoning-engine/tracing_agents_in_reasoning_engine.ipynb

Cloud Trace reads project_id from a different source. In order to get the correct project_id, the call to auth.authenticate_user needs to specify the project_id.
Fixes #852

fix: Specify project id in auth call in tracing notebook

---

conversation/chat-app/.prettierrc
conversation/chat-app/src/routes/+page.svelte
conversation/chat-app/svelte.config.js

This PR is a followup to the version bumps in #1006 from dependabot, as it updates the config for the conversation/chat-app  to avoid this error at build time:
```
$ npm run build
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'svelte-preprocess'
imported from generative-ai/conversation/chat-app/svelte.config.js
```
The fix is to remove references to `svelte-preprocess` from `svelte.config.js` since its no longer needed per the [Svelte static site adapter docs](https://kit.svelte.dev/docs/adapter-static).

fix: Update web app config for conversation/chat-app related to static site generation

---

language/orchestration/langchain/intro_langchain_palm_api.ipynb

- To address the Qwiklabs quota restrictions, we've updated the document to utilize document indices 40 to 60. This modification allows us to complete the lab without causing quota errors.

fix: Updated the intro_langchain_palm_api.ipynb notebook

---

gemini/grounding/intro-grounding-gemini.ipynb
gemini/reasoning-engine/tutorial_vertex_ai_search_rag_agent.ipynb

This PR is related to #1012 as it adds troubleshooting steps to the Grounding + Vertex AI Search sample notebook:
* Need to create a data store and a search app, otherwise the query will throw a 400 error if only a data store is in use.
* Need to wait for the indexing to be complete, otherwise the query will return an empty string.
Relevant additions:
---

docs: Update steps in Grounding notebook to include creating a search app in Vertex AI Search

---

gemini/function-calling/sql-talk-app/app.py

This PR adds improved error catching to the SQL Talk app. Currently, if an error is encountered due to a malformed generated SQL query or an error executing the tools / functions, then a full stack trace will appear in the app. With this PR, errors are caught at the SQL execution level and top-level application and rendered in the app (and persisted in the message history) without a full stack trace.
Special thanks to @mona19 for suggesting this change and providing a sample implementation! 🙏 
How friendlier errors will appear now instead of a full stack trace:
---
---

feat: Improve error catching in the SQL Talk app (Gemini Function Calling)

---

gemini/sample-apps/e2e-gen-ai-app-starter-pack/README.md

Add gcloud auth application-default login command before running gcloud auth application-default set-quota-project $PROJECT_ID (otherwise the latter will fail)
- [] You are listed as the author in your notebook or README file.

fix: Update README.md to add missing application-default login step

---

gemini/reasoning-engine/tutorial_cloud_sql_pg_rag_agent.ipynb

Add missing sqlalchemy import in cloud sql tutorial.
Affected lines:
https://github.com/GoogleCloudPlatform/generative-ai/blob/aff5724b3ebb8b7e6292cba8027ec2e4d24a95b9/gemini/reasoning-engine/tutorial_cloud_sql_pg_rag_agent.ipynb#L348-L350

fix: add missing sqlalchemy text import in cloud sql tutorial

---

gemini/sample-apps/e2e-gen-ai-app-starter-pack/app/utils/tracing.py
gemini/sample-apps/e2e-gen-ai-app-starter-pack/tests/unit/test_utils/test_tracing_exporter.py

Avoid to create a GCS bucket from Python as non transparent for the user. This might also cause errors with Terraform IaC.

fix: starter pack tracing utils gcs export

---

gemini/sample-apps/genwealth/api/package-lock.json
gemini/sample-apps/genwealth/api/package.json

Reverts GoogleCloudPlatform/generative-ai#1242
This is a breaking change that broke the deployment process. Example error:
```
> [api-build 5/5] RUN npx tsc --outDir /dist:
18.11 index.ts(111,59): error TS2769: No overload matches this call.
18.11   The last overload gave the following error.
18.11     Argument of type '(req: Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>, res: Response<any, Record<string, any>, number>) => Promise<...>' is not assignable to parameter of type 'RequestHandlerParams<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.
18.11       Type '(req: Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>, res: Response<any, Record<string, any>, number>) => Promise<...>' is not assignable to type …
```

Revert "chore(deps): bump cookie and express in /gemini/sample-apps/genwealth/api"

---

gemini/function-calling/function_calling_data_structures.ipynb

This is related to #1342 and [this bug](https://issuetracker.google.com/issues/376170319), but this PR does not fix the underlying issue. Rather, this PR fixes a couple of related issues in the sample notebook that cause errors:
* Changes the nested data structure types from `array` to `object` because of the use of `properties` and how Gemini 1.5 enforces this syntax
* Fixes an issue with the required key mismatched with the actual key name (spaces should not be present in parameter names or Gemini will throw an error)

fix: Update required key name and nested data structure types in Function Calling Data Structures Notebook

---

gemini/batch-prediction/intro_batch_prediction.ipynb
gemini/batch-prediction/intro_batch_prediction_using_bigquery_input.ipynb

Update the batch prediction API namespace. 
The new API is available in Vertex AI SDK for Python 1.71.0.

refactor: Update the batch prediction API namespace

---

vision/use-cases/hey_llm/src/main.ts

Add missing `aspectRatio` arg to IMAGEN's JSDoc.

fix: add missing aspect ratio arg to JSDoc.

---

gemini/reasoning-engine/tutorial_langgraph_rag_agent.ipynb

This PR fixes the sample data path in GCS to one that is publicly accessible.

fix: Fix GCS URLs for sample data in tutorial_langgraph_rag_agent notebook

---

gemini/sample-apps/genwealth/api/package-lock.json
gemini/sample-apps/genwealth/api/package.json

This reverts commit cb854717643d2f2ed008d0c25958b91c2f984111 which contained breaking changes to the genwealth sample app deployment.

Revert "chore(deps): update dependency @types/express to v5 (#1176)"

---

notebook_template.ipynb

I've seen an engineer got stuck with the "session crash" message with our notebooks. I shared this with @polong-lin and he suggested me to create a PR for a fix to the template.

fix: Add a "session crash" warning

---

conversation/chat-app/package-lock.json
conversation/chat-app/package.json

This PR is a followup to #1460 but with correct updates to `package.json` and `package-lock.json`, and updates svelte-kit, vite, and related npm dependencies in https://github.com/GoogleCloudPlatform/generative-ai/tree/main/conversation/chat-app.

chore: Update svelte-kit, vite, and related npm deps in chat-app

---

gemini/sample-apps/finance-advisor-spanner/README.md
gemini/sample-apps/finance-advisor-spanner/Schema-Operations.sql

fix: updated finance-advisor-spanner to an up-to-date embedding model

---

gemini/multimodal-live-api/real_time_rag_retail_gemini_2_0.ipynb

chore: add documentation links and what's next block

---

gemini/context-caching/intro_context_caching.ipynb
gemini/controlled-generation/intro_controlled_generation.ipynb
gemini/function-calling/intro_function_calling.ipynb
gemini/grounding/intro-grounding-gemini.ipynb
gemini/long-context/intro_long_context.ipynb
gemini/prompts/intro_prompt_design.ipynb
gemini/rag-engine/intro_rag_engine.ipynb
gemini/responsible-ai/gemini_prompt_attacks_mitigation_examples.ipynb
gemini/responsible-ai/gemini_safety_ratings.ipynb

chore: Add Banner about Gen AI SDK to Notebooks using Vertex AI SDK

---

.github/actions/spelling/allow.txt
vision/getting-started/imagen3_editing.ipynb

Correct the Imagen 3 editing example to use "bgswap" instead of "inpainting-insert"

fix: change edit mode for product background editing

---

.github/actions/spelling/allow.txt
gemini/getting-started/intro_gemini_2_0_flash_thinking_mode.ipynb

feat: add new notebook for Gemini 2.0 Flash Thinking mode

---

.github/actions/spelling/line_forbidden.patterns
gemini/use-cases/code/analyze_codebase_with_gemini_1_5_pro.ipynb

- Add Context Caching to save on latency and request costs
- Change clone to only pull last 2 commits to decrease clone time
- Added myself to Authors list
- Added more robust project ID entry
- Moved imports to the top
- Changed `get_github_issue()` to use `PyGitHub`
- Changed prints to use Markdown or regular printing when streaming
- Create new model object with Function Calling Tool
- Moved git diff into separate function

fix: Updates to Codebase Analysis Notebook

---

gemini/multimodal-live-api/websocket-demo-app/frontend/pcm-processor.js

fix: Correct syntax errors in PCM processor

---

gemini/multimodal-live-api/websocket-demo-app/README.md

Update the spacing in the Multimodal Live Demo README so the list is ordered correctly.

fix: demo readme formatting

---

gemini/multimodal-live-api/websocket-demo-app/README.md

doc: removes errant semicolon, fix: #1578

---

gemini/multimodal-live-api/websocket-demo-app/README.md

Further updates to multimodal docs README to clarify Cloud Shell usage 
- proper substitution within frontend/scripts.js (instead of index.html)
- entry of project ID in UX (not full model path)
- [ x] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
Fixes #1581  🦕

doc: updates to clarify cloud shell usage, fixes #1581

---

gemini/use-cases/retrieval-augmented-generation/utils/intro_multimodal_rag_utils.py

As described in the issue [1571](https://github.com/GoogleCloudPlatform/generative-ai/issues/1571) the gecko version can't load if it's specified as the latest, it's also not recommended by the documentation, I've changed it to the version 003.
Fixes ##1571 🦕

fix: textembedding gecko 003 change from latest

---

gemini/use-cases/retrieval-augmented-generation/multimodal_rag_langchain.ipynb

The [google-10k-sample-14pages.pdf](https://storage.googleapis.com/github-repo/rag/multimodal_rag_langchain/google-10k-sample-14pages.pdf) needed for the gemini/use-cases/retrieval-augmented-generation/multimodal_rag_langchain.ipynb is present in gs://github-repo/rag/multimodal_rag_langchain/ instead of gs://github-repo/rag/intro_multimodal_rag/. This PR updates the path for downloading it in the rsync command.
Fixes #742

Fix: Update the path to the Google-10K 14 page pdf in multimodal_rag_langchain.ipynb

---

gemini/getting-started/intro_genai_sdk.ipynb

Add Batch Prediction example to Gen AI SDK Intro Notebook.

fix: Add Batch Prediction to Gen AI SDK Intro

---

gemini/reasoning-engine/evaluating_crewai_agent_reasoning_engine_customized_template.ipynb
gemini/reasoning-engine/evaluating_langchain_agent_reasoning_engine_prebuilt_template.ipynb
gemini/reasoning-engine/evaluating_langgraph_agent_reasoning_engine_customized_template.ipynb

Fix: Adding BUCKET_URI env variable

---

gemini/multimodal-live-api/intro_multimodal_live_api_genai_sdk.ipynb

Add back the voice config example for multimodal live API notebook after the SDK update (b/384020181).

fix: Add voice config example for live API

---

gemini/sample-apps/e2e-gen-ai-app-starter-pack/notebooks/getting_started.ipynb

Fix the prompt template being used for evaluation in the starter pack getting_started notebook.

fix:  getting_started notebook starter pack eval prompt template

---

gemini/multimodal-live-api/gradio-voice/.prettierrc
gemini/multimodal-live-api/gradio-voice/app.py
gemini/multimodal-live-api/gradio-voice/header.html
gemini/multimodal-live-api/gradio-voice/requirements.txt

- Add System instruction
- Remove unsupported regions
- Maintenance/style improvements
- Remove extra encoding/decoding

fix: Improvements to Gradio MM Live API Sample App

---

gemini/rag-engine/rag_engine_weaviate.ipynb

fix: Removed typo in rag_engine_weaviate.ipynb

---

gemini/reasoning-engine/tutorial_langgraph.ipynb

- Remove duplicate description "Create custom Python functions to act as tools your AI application can use"
- Replace router description with more specific text about routing logic and tool selection

docs(tutorial_langgraph.ipynb): fix duplicate description in LangGraph tools section

---

gemini/getting-started/intro_gemini_2_0_flash_thinking_mode.ipynb

Change the Thinking model to Thinking model in notebook markdown. 
No code changes.
(Keep the filename as it is for now)

fix: Change Thinking mode to model in markdown

---

gemini/sample-apps/e2e-gen-ai-app-starter-pack/app/patterns/multimodal_live_agent/app/agent.py
gemini/sample-apps/e2e-gen-ai-app-starter-pack/app/patterns/multimodal_live_agent/app/server.py

With the help of kwn@ who raised this bug via mail

fix: starter pack live api async tool calls

---

gemini/evaluation/evaluating_langgraph_agent.ipynb

The code tries to use the model variable as an argument to ChatVertexAI, but at this point, model has not been defined within the function's scope. It's attempting to use the global model variable you set earlier (model = "gemini-1.5-pro"), but since you're also assigning to model inside the function, Python treats it as a local variable, and it hasn't been assigned a value yet.

fix: Renamed the variable "model" to "llm"

---

gemini/sample-apps/gemini-quart-cloudrun/README.md
gemini/sample-apps/gemini-quart-cloudrun/app/app.py

Updated the model name to gemini-2.0-flash-001.

fix: update the model name

---

gemini/reasoning-engine/langgraph_human_in_the_loop.ipynb

fix: missing importing package in langgraph-human-in-the-loop

---

workshops/ai-agents/ai_agents_for_engineers.ipynb

This PR fixes an issue in the AI agents workshop notebook. The commented out library was causing the packages after it (e.g., `langchain-community`) to not get installed.

fix: Correct issue with package installation in Vertex AI SDK in AI agents workshop notebook

---

gemini/agent-engine/evaluating_langchain_agent_engine_prebuilt_template.ipynb
gemini/agent-engine/intro_agent_engine.ipynb
gemini/agent-engine/langgraph_human_in_the_loop.ipynb
gemini/agent-engine/tracing_agents_in_agent_engine.ipynb
gemini/agent-engine/tutorial_alloydb_rag_agent.ipynb
gemini/agent-engine/tutorial_cloud_sql_pg_rag_agent.ipynb
gemini/agent-engine/tutorial_google_maps_agent.ipynb
gemini/agent-engine/tutorial_vertex_ai_search_rag_agent.ipynb

This PR is a followup to #1787 that fixes imports in Agent Engine due to different namespaces in current Vertex AI SDK release. Where we use pre-built templates, we need to use the `from vertexai.preview.reasoning_engines import [Langgraph|Langchain|AG2]Agent` namespace. Where we perform CRUD operations on agents, we need to use the `from vertexai import agent_engines` namespace.

fix: Update imports in Agent Engine notebooks when using LangChain & LangGraph pre-built templates

---

gemini/sample-apps/photo-discovery/ag-web/ag_setup_re.ipynb

This PR is a followup to https://github.com/GoogleCloudPlatform/generative-ai/pull/1787 and https://github.com/GoogleCloudPlatform/generative-ai/pull/1794 that fixes imports in Agent Engine due to different namespaces in current Vertex AI SDK release

fix: Update notebook from reasoning engine to agent engine

---

gemini/tuning/sft_gemini_on_image_captioning.ipynb
gemini/tuning/sft_gemini_on_multiple_images.ipynb
gemini/tuning/sft_gemini_qa.ipynb
gemini/tuning/sft_gemini_summarization.ipynb

- Additional formatting updates

chore: Formatting for Tuning Notebooks

---

gemini/use-cases/intro_multimodal_use_cases.ipynb

This pull request addresses a TypeError that occurs when passing exclude_patterns argument as a list to the ingest function from the gitingest library. The error message "TypeError: unhashable type: 'list'" indicates that the library's internal logic requires "exclude_patterns" to be a hashable type, such as a set.
This PR changes the "exclude_patterns" variable from a list to a set using curly braces {}. This ensures that the exclude_patterns argument is of the correct type, preventing the TypeError and ensuring the ingest function works as intended.
This change was made in response to encountering this error while working with the code in colab, believing this change is a necessary improvement to prevent similar issues for other users.

fix: Change exclude_patterns to a set to avoid TypeError

---

gemini/agents/research-multi-agents/ev_agent/agent_handler/agent_03_QueryAnalysisAgent.py

Colab Building a Research Multi Agent System - a Design Pattern Overview with Gemini 2.0
https://colab.research.google.com/github/GoogleCloudPlatform/generative-ai/blob/main/gemini/agents/research-multi-agents/intro_research_multi_agents_gemini_2_0.ipynb
has a bug when run
```py
results = await agent.execute(
"Show EV charging coverage in Chicago"
)
```
error:
```
💥 Error in execution: 'entities'
KeyError Traceback (most recent call last)
/content/ev_agent/agent_handler/agent_01_ExecutionAgent.py in execute(self, query)
81 self._debug_print(results, "green")
---> 82 self.output_type = str(results["query_analysis"]["entities"]["output_type"])
83
KeyError: 'entities'
```
After some debug, i figure out the redundant code make this a bug, so i delete it
```
'Could not extract required …
```

fix: ev-agent error extract entities

---

gemini/agent-engine/tutorial_langgraph.ipynb

Currently there are two issues in `intro to langgraph` notebook:
1. When deploy the agent, there is an error in the pickle file: AttributeError: 'FieldInfo' object has no attribute '_qualifiers'
2. When send a query to remote agent, there is an error in response: 'Error: TypeError("get_product_details() missing 1 required keyword-only argument: \'product_name\'")\n Please fix your mistakes.'
The first error can be fixed by adding a fixed version for pydantic (i.e., "pydantic==2.11.2").
The 2nd error can be fixed by removing the `@tool` decorator
Fixes 409381713 🦕

fix:  Fix `intro to langgraph` notebook.

---

gemini/evaluation/evaluate_models_in_vertex_ai_studio_and_model_garden.ipynb
gemini/prompts/examples/chain_of_thought_react.ipynb
gemini/prompts/examples/question_answering.ipynb
gemini/use-cases/marketing/creative_content_generation.ipynb
vision/getting-started/image_generation.ipynb

Remove runtime reboot to support automated tests.
We're using %pip install to install libraries on the current runtime.

refactor: remove runtime reboot

---

gemini/chat-completions/intro_chat_completions_api.ipynb

Add thinking example in chat completions API
- Remove "Gemini" from API name
- Remove reboot
- Use global endpoint
- Add controlled generation example
- Add thinking budget example

feat: Add thinking example in chat completions API

---

gemini/agent-engine/tracing_agents_in_agent_engine.ipynb

Otherwise, the following import statement
```
from google.cloud import trace_v1 as trace
```
throws an `ImportError`:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-dc4ebb6d09de> in <cell line: 0>()
1 from datetime import datetime, timedelta
2
----> 3 from google.cloud import trace_v1 as trace
4 import pandas as pd
5 from vertexai import agent_engines
ImportError: cannot import name 'trace_v1' from 'google.cloud' (unknown location)
---------------------------------------------------------------------------
```
b/417488922

fix: Fix Trace SDK import error by force-reinstalling dependencies

---

gemini/orchestration/langgraph_gemini_podcast.ipynb

An error pops up while running the audio consolidation using the Audio Segment library as follows:
"Couldn't find ffmpeg or avmpeg - defaulting to ffmpeg, but may not work warn("Couldn't find ffmpeg or avmpeg- defaulting to ffmpeg, but may not work", RuntimeWarning)"
To avoid this error, the ffmpeg package has to be installed on the machine. Added the instruction to install the "ffmpeg" package on the Terminal in the Vertex AI workbench.

Added the pre-requisite for AudioSegment library

---

gemini/getting-started/intro_gemini_2_5_pro.ipynb

Update the thinking budget range for Gemini 2.5 Pro preview to [128, 32768]

fix: Update the thinking budget range

---

.github/actions/spelling/allow.txt
gemini/controlled-generation/intro_controlled_generation.ipynb

Add JSON Schema support for controlled generation
Also re-organize the code to make the flow more clearer.

feat: Add JSON Schema support for controlled generation
